// Definitions for the "Hear the Definition" button.
// Keyed by lowercase word so lookups are case-insensitive.
// Add an entry here whenever you add a word to words.js, or the
// button falls back to a generic line for that word.
const DEFINITIONS = {
  scratch: "To mark or cut a surface with something sharp; also, a thin shallow mark made this way.",
  stream: "A small, narrow river of flowing water.",
  strong: "Having great physical power or force.",
  thread: "A thin strand of cotton, nylon, or other fiber used for sewing.",
  throat: "The passage in the neck that carries food to the stomach and air to the lungs.",
  spring: "The season between winter and summer when plants begin to grow.",
  scream: "A loud, sharp cry of fear, pain, or excitement.",
  screen: "A flat surface that displays pictures or text, like on a TV or computer.",
  spread: "To open out or distribute something over a wide area.",
  squeak: "A short, high-pitched sound.",
  sketch: "A quick, rough drawing.",
  pitch: "A throw of a ball, especially in baseball; also, to throw something forcefully, or how high or low a sound is.",
  catch: "To grab and hold onto something that is moving toward you.",
  badge: "A small emblem of metal or cloth worn to show rank, membership, or achievement.",
  wedge: "A piece of wood or metal that is thick at one end and thin at the other, used to split or hold things apart.",
  fudge: "A soft, sweet candy made from sugar, butter, and milk.",
  judge: "A person who decides the outcome of a court case or contest.",
  ridge: "A long, narrow raised strip of land, often along the top of a hill.",
  bridge: "A structure built over a river, road, or valley so people can cross.",
  edge: "The outer or border line of something, where it ends.",
  coach: "A person who trains and teaches a sports team.",
  toast: "Bread that has been browned by heat.",
  roast: "To cook food, usually meat, slowly using dry heat.",
  coast: "The land along the edge of the ocean.",
  floating: "Resting or moving on top of a liquid, or drifting through the air without sinking or falling.",
  knight: "A medieval soldier who served a king and fought on horseback in armor.",
  knock: "To hit something, especially a door, to get attention.",
  knee: "The joint in the middle of the leg where it bends.",
  kneel: "To go down on one or both knees.",
  know: "To have information or understanding about something in your mind.",
  wrist: "The joint that connects the hand to the arm.",
  write: "To make letters or words on a surface, usually with a pen or pencil.",
  wrong: "Not correct or not true.",
  wreck: "The badly damaged remains of something, such as a car or ship, after an accident.",
  wrap: "To cover something completely by folding paper or cloth around it.",
  gnat: "A tiny flying insect that often bites.",
  gnaw: "To bite or chew on something repeatedly.",
  sign: "A board or notice with words or pictures that gives information.",
  design: "A plan or drawing showing how something will look or be made.",
  assignment: "A task or piece of work given to someone, often for school.",
  honest: "Truthful and not likely to lie, cheat, or steal.",
  honor: "Great respect, or a special recognition or award, given for an achievement or fine character.",
  hour: "A unit of time equal to sixty minutes.",
  ghost: "The spirit of a dead person believed to appear to the living.",
  ghastly: "Extremely unpleasant, shocking, or frightening.",
  echo: "A sound that is reflected off a surface and heard again.",
  chore: "A small, routine task, especially one done around the house.",
  chase: "To run after someone or something to catch it.",
  choose: "To pick one thing or person out of two or more options.",
  choice: "The act of picking between two or more possibilities, or the option picked.",
  beautiful: "Very pleasing to look at or listen to.",
  laughter: "The act or sound of laughing.",
  daughter: "A person's female child.",
  caught: "Grabbed and held onto something moving (past tense of catch).",
  taught: "Showed or explained something to someone so they learn it (past tense of teach).",
  bought: "Paid money to get something (past tense of buy).",
  brought: "Carried or led something or someone to a place (past tense of bring).",
  thought: "An idea or opinion formed in the mind; also, the past tense of think.",
  voyage: "A long journey, especially by ship or in space.",
  destroyer: "A small, fast warship.",
  annoy: "To bother or irritate someone slightly.",
  employ: "To give someone a paid job.",
  ground: "The solid surface of the earth.",
  bounce: "To spring back after hitting a surface.",
  mountain: "A very high, steep hill of rock and earth.",
  voice: "The sound a person makes when speaking or singing.",
  noise: "A sound, especially one that is loud or unpleasant.",
  avoid: "To keep away from someone or something.",
  moisture: "Small amounts of water in the air, on a surface, or in a material.",
  ceiling: "The inner surface at the top of a room.",
  receive: "To get or be given something.",
  receipt: "A printed slip that proves a purchase or payment was made.",
  neighbor: "A person who lives next door or nearby.",
  weigh: "To find out how heavy something is.",
  watermelon: "A large fruit with a hard green rind and juicy red flesh.",
  flashlight: "A small, portable electric light powered by batteries.",
  thunderstorm: "A storm with thunder, lightning, and usually heavy rain.",
  skateboard: "A narrow board on wheels that a person rides while standing.",
  earthquake: "A sudden, violent shaking of the ground caused by movement of the earth's crust.",
  backpack: "A bag with straps, carried on the back to hold belongings.",
  rainbow: "An arc of colors that appears in the sky when sunlight shines through rain.",
  snowflake: "A single small ice crystal that falls as snow.",
  firefly: "A small flying beetle that glows in the dark.",
  sunflower: "A tall plant with large yellow petals around a dark center.",
  teammate: "A person who plays on the same team as you.",
  haircut: "The act or style of cutting someone's hair.",
  lighthouse: "A tower with a bright light that warns or guides ships near the coast.",
  playground: "An outdoor area with equipment for children to play on.",
  sandbox: "A low container or pit filled with sand for children to play in.",
  footprint: "The mark left by a foot or shoe on a surface.",
  rowboat: "A small boat moved through the water using oars.",
  sailboat: "A boat that is moved by the wind pushing against its sails.",
  airplane: "A powered aircraft with wings that flies through the air.",
  airport: "A place where aircraft take off, land, and where passengers board.",
  recharge: "To fill a battery with power again, or to restore energy.",
  review: "To look over or study something again, often to check or remember it.",
  return: "To go back to a place, or to give something back.",
  replace: "To put a new or different thing in the place of another.",
  rewrite: "To write something again, usually to improve it.",
  misplace: "To put something in the wrong place and be unable to find it.",
  mistaken: "Wrong about something; having an incorrect belief.",
  mislead: "To give someone a false idea or impression, often unintentionally.",
  misbehave: "To behave badly.",
  misspell: "To spell a word incorrectly.",
  unable: "Not having the power, skill, or means to do something.",
  unwrapped: "Took the wrapping or covering off of something.",
  unfair: "Not treating people equally or justly.",
  unequal: "Not the same in size, amount, or value.",
  unhappy: "Feeling sad rather than glad.",
  careless: "Not giving enough care or attention; likely to make mistakes.",
  fearless: "Having no fear; brave.",
  hopeless: "Having or showing no hope.",
  helpless: "Unable to take care of or defend oneself.",
  harmless: "Not able or likely to cause damage or injury.",
  happier: "More glad or pleased (comparative of happy).",
  heavier: "Having more weight (comparative of heavy).",
  strongest: "Having the most physical power (superlative of strong).",
  fastest: "Moving or able to move at the greatest speed (superlative of fast).",
  quickest: "Taking the least amount of time (superlative of quick).",
  middle: "The point or part that is halfway between two ends or sides.",
  simple: "Easy to understand or do; not complicated.",
  candle: "A stick of wax with a wick in the center that is burned to give light.",
  battle: "A fight between two armies or opposing sides.",
  uncle: "The brother of one's mother or father, or the husband of one's aunt.",
  towel: "A piece of absorbent cloth used for drying the body after bathing.",
  travel: "To go from one place to another, especially over a long distance.",
  barrel: "A large, round container with curved sides, usually made of wood or metal.",
  camel: "A large desert animal with one or two humps on its back, used for carrying loads.",
  squirrel: "A small animal with a long bushy tail that climbs trees and gathers nuts.",
  doctor: "A person trained and licensed to treat sick or injured people.",
  actor: "A person who performs in plays, movies, or television shows.",
  sailor: "A person who works as a member of a ship's crew.",
  visitor: "A person who comes to see a place or another person for a short time.",
  author: "A person who writes a book, article, or other written work.",
  teacher: "A person whose job is to help students learn.",
  worker: "A person who does a job, especially physical or manual labor.",
  player: "A person who takes part in a game or sport.",
  writer: "A person who writes books, stories, or articles.",
  driver: "A person who operates or steers a vehicle.",
  bargain: "Something bought or sold at a good, low price.",
  certain: "Sure about something, without any doubt.",
  except: "Leaving out or not including something or someone.",
  government: "The group of people with the authority to run a country, state, or city.",
  latitude: "The distance of a place north or south of the equator, measured in imaginary lines that circle the globe.",
  longitude: "The distance of a place east or west, measured by imaginary lines that run from the North Pole to the South Pole.",
  compass: "A tool with a needle that always points north, used for finding direction.",
  parallel: "Lines or surfaces that run side by side, always staying the same distance apart and never meeting.",
  recommend: "To suggest that something is good or suitable.",
  bicycle: "A two-wheeled vehicle that you ride by pedaling.",
  abrupt: "Sudden and unexpected.",
  absence: "The state of being away or not present.",
  accident: "An unexpected and unintended event, often causing harm.",
  accomplish: "To succeed in finishing or achieving something.",
  account: "A description or report of an event, or a record kept of money.",
  achieve: "To successfully reach a goal through effort or skill.",
  across: "From one side of something to the other.",
  activity: "Something that is done for enjoyment or as part of a task.",
  adjust: "To change something slightly to make it fit or work better.",
  adopt: "To take a child or animal into your family and raise it as your own; or, to begin using a new idea or method.",
  advantage: "Something that puts you in a better or more favorable position.",
  advice: "A suggestion or recommendation about what someone should do.",
  against: "In opposition to, or touching and leaning on.",
  agree: "To have the same opinion as someone else, or to say yes to something.",
  ahead: "In front, or further forward in space, time, or progress.",
  alarm: "A sound, device, or signal that warns of danger or wakes someone up.",
  alley: "A narrow passage or lane between or behind buildings.",
  alphabet: "The set of letters used to write a language, arranged in a fixed order.",
  already: "Before now, or sooner than expected.",
  always: "At all times; every time, without exception.",
  amount: "A quantity of something.",
  anchor: "A heavy metal device dropped from a ship to keep it from drifting.",
  ancient: "Very old, from a long time ago.",
  anger: "A strong feeling of annoyance or displeasure.",
  angle: "The space between two lines or surfaces that meet at a point, measured in degrees.",
  animal: "A living creature, other than a plant, that can move and feel.",
  ankle: "The joint connecting the foot to the leg.",
  announce: "To make something known publicly.",
  anxious: "Feeling worried or nervous about what might happen.",
  apology: "A statement saying you are sorry for doing something wrong.",
  appear: "To become visible or come into sight.",
  applaud: "To clap one's hands to show approval.",
  apple: "A round fruit with red, green, or yellow skin and firm white flesh.",
  apron: "A piece of clothing worn over the front of the body to protect clothes while cooking or working.",
  area: "A particular part or space within a place, or the size of a surface.",
  argue: "To express disagreement, often with strong feelings.",
  arrive: "To reach a destination or place.",
  artist: "A person who creates art, such as painting, drawing, or music.",
  asleep: "In a state of sleep.",
  assist: "To help someone do something.",
  astronaut: "A person trained to travel and work in space.",
  athlete: "A person who is trained in or skilled at sports or physical exercise.",
  attempt: "An effort to do something, especially something difficult; or, to try to do something.",
  attend: "To be present at an event or place.",
  attention: "Careful focus or notice given to something.",
  attract: "To cause someone or something to come closer or take interest.",
  audience: "A group of people gathered to watch or listen to a performance.",
  august: "The eighth month of the year.",
  aunt: "The sister of one's mother or father, or the wife of one's uncle.",
  autumn: "The season between summer and winter when leaves fall; also called fall.",
  average: "A typical or usual amount, found by adding values together and dividing by how many there are.",
  awake: "Not asleep.",
  award: "A prize given for an achievement.",
  aware: "Having knowledge or realization of something.",
  awesome: "Causing feelings of great admiration or amazement.",
  awful: "Very bad or unpleasant.",
  awkward: "Causing or feeling embarrassment, discomfort, or a lack of ease; not graceful.",
  baggage: "Bags and suitcases packed for traveling.",
  bakery: "A shop where bread, cakes, and pastries are made and sold.",
  balance: "To keep steady without falling by evenly spreading weight; or, a steady state in which weight is spread evenly.",
  balloon: "A small rubber bag that is filled with air or gas until it expands.",
  banana: "A long curved fruit with soft sweet flesh and a yellow peel.",
  bandage: "A strip of material used to wrap and protect a wound.",
  banish: "To send someone away from a place, usually as punishment.",
  banter: "Light, playful teasing or joking conversation.",
  barely: "Only just; almost not.",
  baron: "A nobleman of a rank just below a viscount.",
  basement: "The floor of a building that is below ground level.",
  basket: "A container made of woven material, used for holding or carrying things.",
  bathe: "To wash one's body, usually in a bathtub.",
  battery: "A device that stores and supplies electrical power.",
  beast: "A large or dangerous animal.",
  beetle: "An insect with a hard, shiny pair of wing covers.",
  before: "Earlier than a particular time or event.",
  beggar: "A person who lives by asking others for money or food.",
  beginner: "A person who is just starting to learn or do something.",
  behave: "To act in a particular way, especially in a proper or acceptable manner.",
  behind: "At or toward the back of something.",
  belief: "A feeling that something is true or real, even without proof.",
  belong: "To be the property of, or to be a member of a group.",
  beneath: "In a lower position than something else; underneath.",
  benefit: "An advantage or helpful effect gained from something.",
  berry: "A small, round, juicy fruit without a pit.",
  between: "In the space or time separating two things.",
  beyond: "On the far side of, or further than, something.",
  billion: "The number 1,000,000,000; a thousand million.",
  blanket: "A large piece of soft cloth used as a cover for warmth.",
  bleed: "To lose blood from the body, usually from a wound.",
  blender: "A kitchen appliance that mixes or purees food using a spinning blade.",
  blizzard: "A severe snowstorm with strong winds.",
  blossom: "To produce flowers, or to grow and develop; also, a flower, especially one that grows on a tree or bush.",
  blouse: "A loose-fitting shirt worn by women or girls.",
  blueberry: "A small, round, dark blue berry that grows on a bush.",
  blunder: "A careless or stupid mistake.",
  blush: "To become red in the face, usually from embarrassment.",
  board: "A long, flat piece of wood or other material.",
  boast: "To talk with too much pride about one's own achievements.",
  body: "The whole physical structure of a person or animal.",
  boil: "To heat a liquid until it bubbles and turns to steam.",
  bold: "Confident and willing to take risks; also describes thick, heavy print or lines that stand out clearly.",
  bolt: "A metal pin or rod, often with a nut, used to fasten things together.",
  bomb: "A weapon designed to explode and cause damage.",
  bond: "A close connection or relationship between people, or something that joins things together.",
  bone: "One of the hard parts that make up the skeleton of a body.",
  bonnet: "A soft hat tied under the chin, often worn by babies.",
  bonus: "An extra reward or amount given in addition to what is expected.",
  bookcase: "A piece of furniture with shelves for holding books.",
  boomerang: "A curved piece of wood that can be thrown so that it returns to the thrower.",
  border: "The line that separates two areas, countries, or regions.",
  bore: "To make someone feel uninterested or tired by being dull.",
  boring: "Not interesting; causing a person to feel tired or restless.",
  borrow: "To take and use something with the intention of returning it.",
  boss: "A person who is in charge of and gives orders to others at work.",
  bother: "To cause someone trouble, worry, or annoyance.",
  bottle: "A container, usually made of glass or plastic, used for holding liquids.",
  bottom: "The lowest part or point of something.",
  bound: "A leap or jump; also describes something tied firmly, or certain to happen.",
  boundary: "A line that marks the limit or edge of an area.",
  bouquet: "A bunch of flowers arranged together, often as a gift.",
  bow: "A knot tied with two or more loops, often made from ribbon, used as a decoration; also, to bend the body forward, or a weapon used to shoot arrows.",
  bowl: "A round, deep dish used for holding food or liquid.",
  boxer: "A person who fights in the sport of boxing.",
  brain: "The organ inside the head that controls thought, memory, and feeling.",
  brake: "A device used to slow down or stop a moving vehicle.",
  branch: "A part of a tree that grows out from the trunk.",
  brand: "A particular kind or make of product, identified by a name or symbol.",
  brave: "Showing courage; not afraid to face danger or pain.",
  bravery: "Courageous behavior in the face of danger or fear.",
  bread: "A food made from flour, water, and yeast that is baked.",
  break: "To cause something to separate into pieces, often suddenly.",
  breakfast: "The first meal of the day, eaten in the morning.",
  breast: "The front upper part of the chest.",
  breath: "The air taken into or let out of the lungs.",
  breathe: "To take air into the lungs and let it out again.",
  breeze: "A light, gentle wind.",
  bribe: "To offer someone money or a gift to dishonestly persuade them to do something; or, the money or gift offered.",
  brick: "A rectangular block of baked clay used for building.",
  bride: "A woman who is about to be married or who has just been married.",
  brief: "Lasting only a short time; short.",
  bright: "Giving off or filled with a lot of light; also, very smart.",
  brilliant: "Extremely bright, or extremely intelligent or skillful.",
  brisk: "Quick and energetic.",
  broad: "Large in width or extent, or covering a wide range.",
  broccoli: "A green vegetable with a thick stalk and clusters of small flower buds.",
  broil: "To cook food directly under or over high heat.",
  broken: "Damaged and separated into pieces, or no longer working.",
  bronze: "A brownish metal made by mixing copper and tin.",
  brooch: "A piece of jewelry fastened to clothing with a pin.",
  brook: "A small, natural stream of water.",
  broom: "A brush with a long handle, used for sweeping floors.",
  brother: "A boy or man with the same parents as another person.",
  brow: "The forehead, or the ridge of hair above the eye.",
  brown: "A color like that of coffee or soil, made by mixing red, yellow, and black.",
  bruise: "An injury that discolors the skin without breaking it, caused by a hit or fall.",
  brush: "A tool with bristles, used for cleaning, painting, or grooming; or, to clean or smooth something using such a tool.",
  brutal: "Extremely harsh, cruel, or violent.",
  bubble: "A thin ball of liquid filled with air or gas.",
  bucket: "A round, open container with a handle, used for carrying liquids.",
  buckle: "A fastener, usually metal, used to join two ends of a belt or strap.",
  bud: "A small swelling on a plant that develops into a leaf, flower, or shoot.",
  budget: "A plan for how to spend a certain amount of money.",
  buffalo: "A large, heavily built wild ox with curved horns.",
  buffet: "A meal set out on a table where guests serve themselves.",
  buggy: "A small, light carriage or cart, often pushed for a baby.",
  bugle: "A brass instrument similar to a small trumpet, often used in the military.",
  build: "To make something by putting parts or materials together.",
  builder: "A person whose job is to construct buildings.",
  building: "A structure with walls and a roof, such as a house or school.",
  bulb: "The glass part of an electric lamp that gives off light, or the round underground part of certain plants.",
  bulge: "A rounded shape that swells outward from a surface.",
  bull: "An adult male of cattle.",
  bullet: "A small piece of metal shot from a gun.",
  bully: "A person who uses strength or power to frighten or hurt someone weaker; or, to intentionally scare or hurt someone weaker.",
  bump: "A small lump or raised area on a surface; also, a light knock or collision, or to knock into something.",
  bumper: "A bar attached to the front or back of a vehicle to protect it in a collision.",
  bunch: "A group of things growing or fastened together.",
  bundle: "A number of things tied or wrapped together.",
  bungalow: "A small house, usually with only one story.",
  bunk: "A narrow bed, often one of a stacked pair.",
  bunny: "A small rabbit.",
  burden: "A heavy load that is carried, or something difficult that must be dealt with.",
  bureau: "A chest of drawers for storing clothes, or a government department.",
  burglar: "A person who breaks into a building to steal.",
  burial: "The act of placing a dead body into the ground.",
  burn: "To be on fire, or to damage something with fire or heat.",
  burner: "The part of a stove that produces heat for cooking.",
  burrow: "A hole or tunnel dug in the ground by an animal to live in.",
  burst: "To break open or apart suddenly, often with force.",
  bury: "To put something in the ground and cover it with earth.",
  bus: "A large motor vehicle that carries many passengers.",
  bush: "A woody plant smaller than a tree, with many branches.",
  bushel: "A unit for measuring dry goods like fruit or grain.",
  business: "The activity of buying and selling goods or services to make money.",
  busy: "Having a lot to do; not free or idle.",
  butcher: "A person whose job is to cut and sell meat.",
  butter: "A soft, yellow food made from churned cream.",
  butterfly: "An insect with large, often colorful wings.",
  button: "A small disk used to fasten clothing, or a part that is pressed to operate a machine.",
  calendar: "A chart showing the days, weeks, and months of a year.",
  camera: "A device used to take photographs or record video.",
  campground: "An area set aside for camping.",
  special: "Better, different, or more important than what is usual.",
  field: "A large open area of land, often used for growing crops or playing sports.",
  friend: "A person you know well and like, who is not a relative.",
  chief: "A person with the highest rank or authority in a group.",
  piece: "A part or portion of something larger.",
  thief: "A person who steals.",
  grief: "Deep sorrow, especially caused by someone's death.",
  shield: "A flat piece of metal or other material carried for protection against attack.",
  relief: "A feeling of comfort after the end of pain, worry, or distress.",
  yield: "To give way or surrender, or to produce a crop or result.",
  fierce: "Showing strong, aggressive force or intensity.",
  pierce: "To make a hole in something with a sharp point.",
  niece: "The daughter of one's brother or sister.",
  official: "A person who holds a position of authority, such as a referee or government worker; or, something approved by an authority.",
  social: "Relating to activities in which people spend time together.",
  crucial: "Extremely important; necessary for something to happen.",
  financial: "Relating to money or how it is managed.",
  partial: "Existing only in part; not complete.",
  martial: "Relating to fighting or war, as in martial arts.",
  captain: "The leader of a team, or the person in charge of a ship or aircraft.",
  curtain: "A piece of fabric hung to cover a window or to separate spaces.",
  fountain: "A structure that shoots water into the air, often for decoration.",
  villain: "A wicked person, especially one who is the main bad character in a story.",
  complaint: "A statement that something is unsatisfactory or unacceptable.",
  material: "The substance from which something is made, such as cloth or wood.",
  serial: "Happening in a series, one after another, such as a story published in parts.",
  dial: "A circular control, such as on a clock or radio, used to select a setting.",
  trial: "A test to try something out, or a formal examination of evidence in a court.",
  giant: "A being in stories that is much larger than a normal person.",
  radiant: "Shining brightly, or showing happiness clearly.",
  complacent: "Feeling so satisfied that you stop trying or fail to notice problems.",
  patient: "Able to wait calmly without getting upset; also, a person receiving medical care.",
  efficient: "Working well without wasting time, effort, or resources.",
  sufficient: "Enough for a particular purpose.",
  weight: "How heavy something is; also, a heavy object, especially one used for exercise or to hold something in place.",
  freight: "Goods transported by truck, train, ship, or plane.",
  eight: "The number 8.",
  sleigh: "A vehicle on runners, used for traveling over snow, often pulled by animals.",
  vein: "A blood vessel that carries blood toward the heart.",
  reindeer: "A large deer with antlers that lives in cold northern regions.",
  abandon: "To leave completely or give up.",
  ability: "The power or skill to do something.",
  abolish: "To formally put an end to something.",
  absorb: "To take in or soak up.",
  abundant: "Existing or available in large quantities.",
  academic: "Relating to education and scholarship.",
  accent: "A distinctive mode of pronunciation.",
  accept: "To consent to receive something.",
  accompany: "To go somewhere with someone.",
  accurate: "Correct in all details.",
  accuse: "To charge someone with a wrongdoing.",
  acid: "A sour chemical substance.",
  acquire: "To buy or obtain for oneself.",
  action: "The fact or process of doing something.",
  active: "Engaging in physically energetic pursuits.",
  actual: "Existing in fact or reality.",
  adapt: "To become adjusted to new conditions.",
  addition: "The action of adding something to something else.",
  address: "The particulars of the place where someone lives.",
  adequate: "Satisfactory or acceptable in quality.",
  admire: "To look at with respect or warm approval.",
  admit: "To confess to be true.",
  advance: "To move forward in a purposeful way.",
  adventure: "An unusual and exciting experience.",
  advertise: "To describe a product to increase sales.",
  advise: "To offer suggestions about the best course of action.",
  advocate: "To publicly recommend or support.",
  affect: "To make a difference to something.",
  afford: "To have enough money to pay for something.",
  afraid: "Feeling fear or anxiety.",
  agency: "A business or organization providing a specific service.",
  agenda: "A list of items to be discussed at a meeting.",
  agent: "A person who acts on behalf of another.",
  aggressive: "Ready or likely to attack or confront.",
  agriculture: "The science or practice of farming.",
  aid: "Help or support given to someone.",
  aim: "To point or direct a weapon or object at a target.",
  aircraft: "An airplane, helicopter, or other flying machine.",
  airline: "A company that provides regular flights for passengers.",
  ballot: "A system of voting secretly.",
  banner: "A long strip of cloth bearing a slogan or design.",
  barren: "Land too poor to produce vegetation.",
  barrier: "A fence or obstacle that prevents movement.",
  basic: "Forming an essential foundation or starting point.",
  basis: "The underlying support or foundation for an idea.",
  beach: "A pebbly or sandy shore by the ocean.",
  beacon: "A fire or light set up in a high position as a warning or signal.",
  beauty: "A combination of qualities that pleases the sight.",
  become: "To grow to be or develop into.",
  begin: "To start doing something.",
  behavior: "The way in which one acts or conducts oneself.",
  believe: "To accept something as true.",
  besides: "In addition to or apart from.",
  betray: "To deliver to an enemy by treachery.",
  bias: "Prejudice in favor of or against one thing.",
  biography: "An account of someone's life written by someone else.",
  biology: "The scientific study of living organisms.",
  birth: "The emergence of a baby or other young from the body of its mother.",
  biscuit: "A small, typically round cake of bread.",
  bitter: "Having a sharp, pungent taste or smell.",
  blame: "To assign responsibility for a fault or wrong.",
  blast: "A destructive wave of highly compressed air from an explosion.",
  blend: "To mix a substance with another substance.",
  blind: "Unable to see because of injury or disease.",
  block: "A large solid piece of hard material.",
  boiler: "A fuel-burning apparatus for heating water.",
  cabin: "A small wooden shelter or house in a wild area.",
  cable: "A thick rope of wire or nonmetallic fiber.",
  cactus: "A succulent plant with a thick fleshy stem which typically bears spines.",
  cage: "A structure of bars or wires in which birds or animals are confined.",
  calamity: "An event causing great and often sudden damage or distress.",
  calculate: "To determine mathematically.",
  calm: "Not showing or feeling nervousness or anger.",
  camp: "A place where tents or temporary shelters are set up.",
  campaign: "An organized course of action to achieve a goal.",
  campus: "The grounds and buildings of a university or school.",
  canal: "An artificial waterway constructed to allow the passage of boats.",
  cancel: "To decide that a planned event will not take place.",
  cancer: "A disease caused by an uncontrolled division of abnormal cells.",
  candidate: "A person who applies for a job or is nominated for election.",
  canvas: "A strong, coarse unbleached cloth used for oil paintings or tents.",
  canyon: "A deep gorge, typically one with a river flowing through it.",
  capable: "Having the ability or quality necessary to do something.",
  capacity: "The maximum amount that something can contain.",
  capital: "The most important city or town of a country or region.",
  capture: "To take into one's possession or control by force.",
  carbon: "A chemical element found in all organic substances.",
  career: "An occupation undertaken for a significant period of a person's life.",
  careful: "Making sure of avoiding potential danger or mishap.",
  cargo: "Goods carried on a ship, aircraft, or motor vehicle.",
  carol: "A religious folk song or popular hymn, particularly one associated with Christmas.",
  carpet: "A floor covering made of thick woven fabric.",
  carriage: "A four-wheeled passenger vehicle pulled by horses.",
  carrot: "A tapering orange root vegetable.",
  carry: "To support and move someone or something from one place to another.",
  carton: "A light box or container, typically one made of cardboard.",
  carve: "To cut a hard material in order to produce an object or design.",
  cascade: "A small waterfall, typically one of several that fall in stages.",
  case: "An instance of a particular situation; an example.",
  cash: "Money in the form of coins or banknotes.",
  castle: "A large building fortified against attack.",
  casual: "Relaxed and unconcerned.",
  catalog: "A complete list of items, typically one in alphabetical order.",
  category: "A class or division of people or things regarded as having shared characteristics.",
  cattle: "Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk.",
  cause: "A person or thing that acts, happens, or exists in such a way that some specific thing happens as a result.",
  caution: "Care taken to avoid danger or mistakes.",
  cautious: "Avoidance of potential risks.",
  cave: "A natural underground chamber in a hillside or cliff.",
  cavity: "An empty space within a solid object.",
  cease: "To bring or come to an end.",
  damage: "Harm caused to something as to impair its value or usefulness.",
  danger: "The possibility of suffering harm or injury.",
  dangerous: "Able or likely to cause harm or injury.",
  darkness: "The partial or total absence of light.",
  darling: "Used as an affectionate form of address to a beloved person.",
  dash: "To run or travel somewhere in a great hurry.",
  database: "A structured set of data held in a computer.",
  dawn: "The first appearance of light in the sky before sunrise.",
  daylight: "The natural light of the day.",
  debate: "A formal discussion on a particular topic in a public meeting.",
  debris: "Scattered pieces of waste or remains.",
  decade: "A period of ten years.",
  decay: "The state or process of rotting or decomposition.",
  deceive: "To deliberately cause someone to believe something that is not true.",
  decide: "To come to a resolution in the mind as a result of consideration.",
  decision: "A conclusion or resolution reached after consideration.",
  declare: "To say something in a solemn and emphatic manner.",
  decline: "To politely refuse an invitation or offer.",
  decorate: "To make something look more attractive by adding extra items.",
  decrease: "To make or become smaller or fewer in size or amount.",
  dedicate: "To devote time or effort to a particular task or purpose.",
  deduct: "To subtract an amount from a total.",
  deed: "An action that is performed intentionally or consciously.",
  deep: "Extending far down from the top or surface.",
  defeat: "To win a victory over someone in a battle or game.",
  defend: "To protect from harm or danger.",
  defense: "The action of defending from or resisting attack.",
  defiance: "Bold disobedience or open resistance.",
  define: "To state or describe exactly the nature or meaning of.",
  definite: "Clearly stated or decided; not vague or doubtful.",
  degree: "A unit of measurement of angles or temperature.",
  delay: "To make someone or something late or slow.",
  delegate: "A person sent or authorized to represent others.",
  deliberate: "Done consciously and intentionally.",
  delicate: "Very fine in texture or structure; easily broken.",
  delicious: "Highly pleasant to the taste.",
  delight: "Great pleasure or joy.",
  deliver: "To bring and hand over a letter or parcel to the recipient.",
  delivery: "The action of delivering letters, packages, or goods.",
  demand: "An insistent and peremptory request, made as of right.",
  democracy: "A system of government by the whole population through elected representatives.",
  demolish: "To pull or knock down a building.",
  demon: "An evil spirit or cruel person.",
  demonstrate: "To clearly show the existence or truth of something by giving proof.",
  denial: "The action of declaring something to be untrue.",
  denounce: "To publicly declare to be wrong or evil.",
  dense: "Closely compacted in substance; thick.",
  density: "The degree of compactness of a substance.",
  dental: "Relating to teeth or dentistry.",
  eager: "Strongly wanting to do or have something.",
  eagle: "A large bird of prey with a massive hooked bill and long broad wings.",
  early: "Happening or done before the usual or expected time.",
  earn: "To obtain money in return for labor or services.",
  earnest: "Resulting from or showing sincere and intense conviction.",
  earth: "The planet on which we live; the world.",
  ease: "Absence of difficulty or effort.",
  easily: "Without high effort or difficulty.",
  east: "The direction toward the point of the horizon where the sun rises.",
  eastern: "Situated in or facing the east.",
  easy: "Achieved without great effort; simple.",
  eclipse: "An astronomical event where one celestial body obscures another.",
  ecology: "The political or scientific study of organisms and their environment.",
  economic: "Relating to the economy or wealth of a country.",
  economy: "The wealth and resources of a country or region.",
  edition: "A particular form or version of a published text.",
  editor: "A person who corrects or changes pieces of text before publication.",
  educate: "To give intellectual, moral, and social instruction to someone.",
  education: "The process of receiving or giving systematic instruction.",
  effect: "A change which is a result or consequence of an action.",
  effective: "Successful in producing a desired or intended result.",
  efficiency: "The state or quality of achieving maximum productivity with minimum wasted effort.",
  effort: "A vigorous or determined attempt.",
  either: "Used before the first of two alternatives to indicate choice.",
  elaborate: "Involving many carefully arranged parts or details.",
  elastic: "Able to resume its normal shape after contraction or stretching.",
  elbow: "The joint between the forearm and the upper arm.",
  elder: "A person of greater age than another.",
  elect: "To choose someone to hold a public office by voting.",
  election: "A formal and organized choice by vote of a person for a political office.",
  electric: "Worked by, charged with, or producing electricity.",
  electricity: "A form of energy resulting from the existence of charged particles.",
  elegant: "Graceful and stylish in appearance or manner.",
  element: "A part or aspect of something abstract, especially one that is essential.",
  elementary: "Relating to the most rudimentary aspects of a subject.",
  elephant: "A very large plant-eating mammal with a prehensile trunk and long tusks.",
  elevate: "To raise or lift something up to a higher position.",
  elevator: "A platform or compartment housed in a shaft for raising and lowering people.",
  eligible: "Having the right to do or obtain something.",
  eliminate: "To completely remove or get rid of something.",
  elite: "A select group that is superior in terms of ability or qualities.",
  eloquent: "Fluent or persuasive in speaking or writing.",
  elsewhere: "In or to another place or somewhere else.",
  elusive: "Difficult to find, catch, or achieve.",
  embargo: "An official ban on trade or other commercial activity with a country.",
  embark: "To go on board a ship or aircraft; to begin a journey.",
  fabric: "Cloth or other material produced by weaving together fibers.",
  fabulous: "Extraordinary, especially extraordinarily good.",
  face: "The front part of a person's head from the forehead to the chin.",
  facility: "A place, amenity, or piece of equipment provided for a particular purpose.",
  fact: "A thing that is known or proved to be true.",
  factor: "A circumstance, fact, or influence that contributes to a result.",
  factory: "A building where goods are manufactured or assembled chiefly by machine.",
  faculty: "The teaching staff of a university or school.",
  fade: "To lose color or brightness gradually.",
  failure: "Lack of success in doing or achieving something.",
  faint: "Lacking clarity, brightness, volume, or distinctness.",
  fair: "Treating people equally without favoritism or discrimination.",
  faith: "Complete trust or confidence in someone or something.",
  faithful: "Remaining loyal and steadfast.",
  maintain: "To keep something in good condition.",
  majority: "More than half of a total number.",
  malice: "The desire to harm someone else.",
  mammal: "A warm-blooded animal with hair or fur.",
  mandatory: "Required by a law or rule.",
  maneuver: "A planned movement or clever strategy.",
  manifest: "Clear or obvious to the eye or mind.",
  manipulate: "To handle or control skillfully.",
  manner: "The way in which something is done or happens.",
  manuscript: "A handwritten or typed book or document.",
  marathon: "A long-distance running race.",
  margin: "The blank border on each side of a page.",
  marvel: "To filled with wonder or astonishment.",
  mascot: "A person or animal used to bring good luck.",
  massive: "Large, heavy, and solid.",
  masterpiece: "A work of outstanding artistry or skill.",
  mature: "Fully grown or behaving like an adult.",
  maximum: "The greatest amount or number possible.",
  meadow: "A piece of grassland.",
  measure: "To find the size or amount of something.",
  mechanic: "A person who repairs and maintains machinery.",
  media: "The main means of mass communication.",
  mediate: "To settle a dispute between two groups.",
  medicinal: "Having healing properties for illnesses.",
  medieval: "Relating to the Middle Ages.",
  mediocre: "Of only moderate or low quality.",
  melancholy: "A feeling of pensive sadness.",
  melody: "A sequence of notes that makes up a tune.",
  memorable: "Worth remembering or easily remembered.",
  menace: "A person or thing that is likely to cause harm.",
  mention: "To refer to something briefly.",
  mentor: "An experienced and trusted adviser.",
  merchant: "A person involved in wholesale trade.",
  mercy: "Compassion or forgiveness shown to someone.",
  mere: "Used to emphasize how small or insignificant something is.",
  merge: "To combine or blend together.",
  merit: "The quality of being particularly good or worthy.",
  metaphor: "A figure of speech comparing two things without using \"like\" or \"as\".",
  method: "A particular procedure for accomplishing something.",
  meticulous: "Showing great attention to detail.",
  microscope: "An instrument used to see very small objects.",
  migration: "Seasonal movement of animals from one region to another.",
  mild: "Gentle or not severe.",
  mimic: "To imitate someone's actions or words.",
  minimum: "The smallest amount required or possible.",
  minuscule: "Extremely small or tiny.",
  miracle: "An extraordinary and welcome event that seems impossible.",
  mischief: "Playful misbehavior or trouble.",
  miserable: "Very unhappy or uncomfortable.",
  misfortune: "Bad luck or an unfortunate event.",
  mission: "An important assignment given to a person or group.",
  mixture: "A substance made by mixing other substances together.",
  mobilize: "To organize or prepare for action.",
  model: "A three-dimensional representation of a person or thing.",
  moderate: "Average in amount, intensity, or quality.",
  modest: "Humble about one's achievements.",
  modify: "To make partial changes to something.",
  molecule: "The smallest unit of a chemical compound.",
  momentum: "The quantity of motion of a moving body.",
  monarch: "A sovereign head of state, like a king or queen.",
  monitor: "To observe and check the progress of something.",
  monopoly: "Exclusive control of a commodity or service.",
  monotonous: "Dull, tedious, and lacking in variety.",
  monument: "A statue or building built to remember a person or event.",
  morale: "The confidence and enthusiasm of a person or group.",
  mortal: "Subject to death or causing death.",
  motivate: "To provide someone with a reason to do something.",
  motive: "A reason for doing something.",
  mourn: "To feel deep sadness or grief.",
  multiple: "Consisting of many parts or elements.",
  multitude: "A large number of people or things.",
  municipal: "Relating to a city or town government.",
  murmur: "A soft, indistinct sound made by a person speaking.",
  muscle: "A tissue in the body that produces movement.",
  mutual: "Experienced or shared by two or more parties.",
  myriad: "A countless or extremely great number.",
  mysterious: "Difficult or impossible to understand or explain.",
  myth: "A traditional story concerning the early history of people.",
  naive: "Showing a lack of experience or wisdom.",
  narrative: "A spoken or written account of connected events; a story.",
  narrow: "Small in width.",
  nasal: "Relating to the nose.",
  native: "Associated with the place of one's birth.",
  natural: "Existing in or caused by nature.",
  nausea: "A feeling of sickness with an inclination to vomit.",
  navigate: "To plan and direct the route or course of a ship or car.",
  necessary: "Needed to be done or achieved.",
  neglect: "To fail to care for properly.",
  negotiate: "To try to reach an agreement through discussion.",
  neutral: "Not supporting either side in an argument.",
  nimble: "Quick and light in movement.",
  nominate: "To propose someone for election or an award.",
  nonchalant: "Feeling or appearing casually calm and relaxed.",
  nonsense: "Spoken or written words that have no meaning.",
  norm: "Something that is usual, typical, or expected.",
  nostalgia: "A sentimental longing for the past.",
  notable: "Worthy of attention or notice.",
  notify: "To inform someone or give notice.",
  notion: "A conception of or belief about something.",
  notorious: "Famous or well known, typically for some bad quality.",
  novelty: "The quality of being new, original, or unusual.",
  novice: "A person new to and inexperienced in a job or situation.",
  nuance: "A subtle distinction or variation.",
  nuisance: "A person, thing, or circumstance causing inconvenience.",
  numerous: "Great in number; many.",
  nurture: "To care for and encourage the growth or development of.",
  nutrient: "A substance that provides nourishment essential for life.",
  obedient: "Complying or willing to comply with orders or rules.",
  object: "A material thing that can be seen and touched.",
  objective: "Not influenced by personal feelings or opinions.",
  obligation: "An act or course of action to which a person is bound.",
  oblivious: "Not aware of or concerned about what is happening around.",
  obnoxious: "Extremely unpleasant.",
  obscure: "Not discovered or known about; uncertain.",
  observant: "Quick to notice things.",
  obstacle: "A thing that blocks one's way or prevents progress.",
  obstinate: "Stubbornly refusing to change one's opinion.",
  obtain: "To get or acquire something.",
  obvious: "Easy to see or understand.",
  occasion: "A particular time or special event.",
  occupy: "To take up a space or time.",
  occur: "To happen or take place.",
  ocean: "A very large expanse of sea.",
  offend: "To cause someone to feel upset or insulted.",
  ominous: "Giving the impression that something bad is going to happen.",
  omit: "To leave out or exclude.",
  opinion: "A view or judgment formed about something.",
  opponent: "Someone who competes against another in a contest.",
  opportunity: "A set of circumstances that makes it possible to do something.",
  oppose: "To actively resist or refuse to comply with.",
  optimistic: "Hopeful and confident about the future.",
  option: "A thing that is or may be chosen.",
  ordinary: "With no special or distinctive features; normal.",
  organism: "An individual animal, plant, or single-celled life form.",
  origin: "The point or place where something begins.",
  original: "Present or existing from the beginning.",
  ornament: "A thing used to make something look more attractive.",
  outrageous: "Shockingly bad or excessive.",
  overcome: "To succeed in dealing with a problem or difficulty.",
  oxygen: "A gas that enters the blood through the lungs.",
  pace: "The speed at which someone or something moves.",
  pacify: "To quell the anger or agitation of.",
  painstaking: "Done with or employing great care and thoroughness.",
  pamphlet: "A small booklet containing information about a single subject.",
  panic: "Sudden uncontrollable fear or anxiety.",
  paradox: "A statement that seems absurd but may be true.",
  paralyze: "To cause a person or animal to lose the ability to move.",
  paramount: "More important than anything else; supreme.",
  paraphrase: "To express the meaning of using different words.",
  parasite: "An organism that lives in or on another organism.",
  pardon: "To forgive or excuse an offense.",
  participate: "To take part in an action or event.",
  particle: "A minute portion of matter.",
  particular: "Specific or special.",
  passion: "Strong and barely controllable emotion.",
  passive: "Accepting or allowing what happens without resistance.",
  patience: "The capacity to accept delay or trouble without getting angry.",
  patriot: "A person who vigorously supports their country.",
  patronize: "To frequent a shop or theater as a customer.",
  pause: "A temporary stop in action or speech.",
  pavilion: "A light, open building used for shelter or exhibits.",
  peaceful: "Free from disturbance; tranquil.",
  peculiar: "Strange or odd; unusual.",
  pedestrian: "A person walking along a road or in a developed area.",
  peer: "A person of the same age, status, or ability.",
  penalize: "To subject to a penalty or punishment.",
  pensive: "Engaged in, involving, or reflecting deep or serious thought.",
  perceive: "To become aware or conscious of something.",
  perception: "The ability to see, hear, or become aware of something through the senses.",
  perennial: "Lasting or existing for a long or apparently infinite time.",
  perfect: "Having all required elements or qualities; flawless.",
  peril: "Serious and immediate danger.",
  perimeter: "The continuous line forming the boundary of a closed geometric figure.",
  perish: "To suffer death, typically in a violent or sudden way.",
  permanent: "Lasting or intended to last or remain unchanged indefinitely.",
  permissible: "Permitted; allowable.",
  perpendicular: "At an angle of 90 degrees to a given line or surface.",
  perpetual: "Never ending or changing.",
  perplex: "To cause someone to feel completely baffled.",
  persevere: "To continue in a course of action even in the face of difficulty.",
  persist: "To continue firmly in an opinion or a course of action.",
  personality: "The combination of characteristics that form an individual's character.",
  perspective: "A particular attitude toward or way of regarding something.",
  persuade: "To convince someone to do something through reasoning.",
  pertain: "To be appropriate, related, or applicable.",
  pertinent: "Relevant or applicable to a particular matter.",
  pessimistic: "Tending to see the worst aspect of things.",
  petition: "A formal written request signed by many people.",
  petrify: "To change into stone or to paralyze with fear.",
  petty: "Of little importance; trivial.",
  phenomenon: "A fact or situation that is observed to exist or happen.",
  philosophy: "The study of the fundamental nature of knowledge and reality.",
  phobic: "Having an extreme or irrational fear of something.",
  phrase: "A small group of words standing together as a conceptual unit.",
  physical: "Relating to the body as opposed to the mind.",
  physician: "A person qualified to practice medicine; a doctor.",
  physics: "The branch of science concerned with nature and properties of matter.",
  physique: "The form, size, and development of a person's body.",
  pinnacle: "The most successful point; the culmination.",
  pioneer: "A person who is among the first to explore or settle a new area.",
  pious: "Devoutly religious.",
  pique: "To stimulate interest or curiosity.",
  pirate: "A person who attacks and robs ships at sea.",
  pitiful: "Deserving or arousing pity.",
  pity: "The feeling of sorrow and compassion caused by the sufferings of others.",
  pivotal: "Of crucial importance in relation to the development of something else.",
  placard: "A poster or sign for public display.",
  placid: "Not easily upset or excited; calm.",
  plague: "A contagious bacterial disease or a widespread affliction.",
  plaintiff: "A person who brings a case against another in a court of law.",
  plateau: "An area of relatively level high ground.",
  plausible: "Seeming reasonable or probable.",
  plea: "A request made in an urgent and emotional manner.",
  pledge: "A solemn promise or undertaking.",
  pliable: "Easily bent; flexible.",
  plight: "A dangerous, difficult, or otherwise unfortunate situation.",
  plot: "The main events of a play, novel, or movie.",
  plunder: "To steal goods from a place or person, typically during a war.",
  plunge: "To jump or dive quickly and energetically.",
  plural: "More than one in number.",
  pneumonia: "An infection that inflames the air sacs in one or both lungs.",
  poach: "To cook an egg without its shell in simmering liquid, or to illegally hunt.",
  poetry: "Literary work in which special intensity is given to the expression of feelings.",
  poignant: "Evoking a keen sense of sadness or regret.",
  poise: "Graceful and elegant bearing in a person.",
  poison: "A substance that is capable of causing illness or death when introduced into an organism.",
  polar: "Relating to the North or South Pole.",
  policy: "A course or principle of action adopted or proposed by a government or individual.",
  polish: "To make the surface of something smooth and shiny by rubbing it.",
  pollute: "To contaminate water, air, or soil with harmful substances.",
  pompous: "Affectedly and irritatingly grand, solemn, or self-important.",
  ponder: "To think about something carefully, especially before making a decision.",
  popular: "Liked, admired, or enjoyed by many people.",
  population: "All the inhabitants of a particular town, area, or country.",
  porous: "Having small spaces or holes through which liquid or air may pass.",
  portable: "Able to be easily carried or moved.",
  portion: "A part of a whole; a serving of food.",
  portray: "To depict someone or something in a work of art or literature.",
  pose: "To assume a particular position in order to be photographed or painted.",
  position: "A place where someone or something is located or has been put.",
  positive: "Consisting in or characterized by the presence rather than the absence of features.",
  possess: "To have or own something.",
  possibility: "A thing that may happen or be the case.",
  postpone: "To cause or arrange for something to take place at a time later than that first scheduled.",
  posture: "The position in which someone holds their body when standing or sitting.",
  potent: "Having great power, influence, or effect.",
  potential: "Having or showing the capacity to become something in the future.",
  pottery: "Pots, dishes, and other articles made of baked clay.",
  poverty: "The state of being extremely poor.",
  practical: "Concerned with the actual doing or use of something rather than with theory.",
  praise: "To express warm approval or admiration of.",
  prance: "To move with high, springy steps.",
  precarious: "Not securely held or in position; dangerously likely to fall or collapse.",
  precaution: "A measure taken in advance to prevent something dangerous from happening.",
  precede: "To come before something in time, order, or position.",
  precedent: "An earlier event or action that is regarded as an example or guide.",
  precious: "Of great value; not to be wasted or treated carelessly.",
  precise: "Marked by exactness and accuracy of expression or detail.",
  precision: "The quality, condition, or fact of being exact and accurate.",
  precocious: "Having developed certain abilities or proclivities at an earlier age than usual.",
  predator: "An animal that naturally preys on others.",
  predecessor: "A person who held a job or office before the current holder.",
  predict: "To say or estimate that a specified thing will happen in the future.",
  prediction: "A thing predicted; a forecast.",
  predominant: "Present as the strongest or main element.",
  preface: "An introduction to a book, typically stating its subject, scope, or aims.",
  prefer: "To like one thing better than another.",
  preference: "A greater liking for one alternative over another.",
  prefix: "A word, letter, or number placed before another.",
  prehistoric: "Relating to the period before written history.",
  prejudice: "Preconceived opinion that is not based on reason or actual experience.",
  preliminary: "Denoting an action or event preceding or done in preparation for something fuller or more important.",
  premature: "Occurring or done before the usual or proper time.",
  premium: "An amount to be paid for an insurance policy, or of high quality.",
  premonition: "A strong feeling that something is about to happen, especially something unpleasant.",
  preoccupy: "To engross or distract someone completely.",
  prepare: "To make something ready for use or consideration.",
  preposterous: "Utterly absurd or ridiculous.",
  prerequisite: "A thing that is required as a prior condition for something else to happen.",
  prescribe: "To advise or authorize the use of a medicine or treatment.",
  prescription: "An instruction written by a medical practitioner that authorizes a patient to be provided a medicine.",
  presence: "The state or fact of existing, occurring, or being present in a place.",
  present: "Existing or occurring now.",
  preserve: "To maintain something in its original or existing state.",
  preside: "To be in the position of authority in a meeting or gathering.",
  president: "The elected head of a republican state or an organization.",
  prestige: "Widespread respect and admiration felt for someone or something.",
  prestigious: "Inspiring respect and admiration; having high status.",
  presume: "To suppose that something is the case on the basis of probability.",
  presumptuous: "Failing to observe the limits of what is permitted or appropriate.",
  pretend: "To speak and act so as to make it appear that something is the case when in fact it is not.",
  pretense: "An attempt to make something that is not the case appear true.",
  pretentious: "Attempting to impress by affecting greater importance than is actually possessed.",
  pretext: "A false reason given to justify an action.",
  prevail: "To prove more powerful than opposing forces; to win.",
  prevalent: "Widespread in a particular area or at a particular time.",
  prevent: "To keep something from happening or arising.",
};
