// Definitions for the "Hear the Definition" button.
// Keyed by lowercase word so lookups are case-insensitive.
// Add an entry here whenever you add a word to words.js, or the
// button falls back to a generic line for that word.
const DEFINITIONS = {
  scratch: "To mark or cut a surface with something sharp; also, a thin shallow mark made this way.",
  stream: "A small, narrow river of flowing water.",
  strong: "Having great physical power or force.",
  thread: "A thin strand of cotton, nylon, or other fiber used for sewing.",
  throat: "The passage in the neck that carries food to the stomach and air to the lungs.",
  spring: "The season between winter and summer when plants begin to grow.",
  scream: "A loud, sharp cry of fear, pain, or excitement.",
  screen: "A flat surface that displays pictures or text, like on a TV or computer.",
  spread: "To open out or distribute something over a wide area.",
  squeak: "A short, high-pitched sound.",
  sketch: "A quick, rough drawing.",
  pitch: "A throw of a ball, especially in baseball; also, to throw something forcefully, or how high or low a sound is.",
  catch: "To grab and hold onto something that is moving toward you.",
  badge: "A small emblem of metal or cloth worn to show rank, membership, or achievement.",
  wedge: "A piece of wood or metal that is thick at one end and thin at the other, used to split or hold things apart.",
  fudge: "A soft, sweet candy made from sugar, butter, and milk.",
  judge: "A person who decides the outcome of a court case or contest.",
  ridge: "A long, narrow raised strip of land, often along the top of a hill.",
  bridge: "A structure built over a river, road, or valley so people can cross.",
  edge: "The outer or border line of something, where it ends.",
  coach: "A person who trains and teaches a sports team.",
  toast: "Bread that has been browned by heat.",
  roast: "To cook food, usually meat, slowly using dry heat.",
  coast: "The land along the edge of the ocean.",
  floating: "Resting or moving on top of a liquid, or drifting through the air without sinking or falling.",
  knight: "A medieval soldier who served a king and fought on horseback in armor.",
  knock: "To hit something, especially a door, to get attention.",
  knee: "The joint in the middle of the leg where it bends.",
  kneel: "To go down on one or both knees.",
  know: "To have information or understanding about something in your mind.",
  wrist: "The joint that connects the hand to the arm.",
  write: "To make letters or words on a surface, usually with a pen or pencil.",
  wrong: "Not correct or not true.",
  wreck: "The badly damaged remains of something, such as a car or ship, after an accident.",
  wrap: "To cover something completely by folding paper or cloth around it.",
  gnat: "A tiny flying insect that often bites.",
  gnaw: "To bite or chew on something repeatedly.",
  sign: "A board or notice with words or pictures that gives information.",
  design: "A plan or drawing showing how something will look or be made.",
  assignment: "A task or piece of work given to someone, often for school.",
  honest: "Truthful and not likely to lie, cheat, or steal.",
  honor: "Great respect, or a special recognition or award, given for an achievement or fine character.",
  hour: "A unit of time equal to sixty minutes.",
  ghost: "The spirit of a dead person believed to appear to the living.",
  ghastly: "Extremely unpleasant, shocking, or frightening.",
  echo: "A sound that is reflected off a surface and heard again.",
  chore: "A small, routine task, especially one done around the house.",
  chase: "To run after someone or something to catch it.",
  choose: "To pick one thing or person out of two or more options.",
  choice: "The act of picking between two or more possibilities, or the option picked.",
  beautiful: "Very pleasing to look at or listen to.",
  laughter: "The act or sound of laughing.",
  daughter: "A person's female child.",
  caught: "Grabbed and held onto something moving (past tense of catch).",
  taught: "Showed or explained something to someone so they learn it (past tense of teach).",
  bought: "Paid money to get something (past tense of buy).",
  brought: "Carried or led something or someone to a place (past tense of bring).",
  thought: "An idea or opinion formed in the mind; also, the past tense of think.",
  voyage: "A long journey, especially by ship or in space.",
  destroyer: "A small, fast warship.",
  annoy: "To bother or irritate someone slightly.",
  employ: "To give someone a paid job.",
  ground: "The solid surface of the earth.",
  bounce: "To spring back after hitting a surface.",
  mountain: "A very high, steep hill of rock and earth.",
  voice: "The sound a person makes when speaking or singing.",
  noise: "A sound, especially one that is loud or unpleasant.",
  avoid: "To keep away from someone or something.",
  moisture: "Small amounts of water in the air, on a surface, or in a material.",
  ceiling: "The inner surface at the top of a room.",
  receive: "To get or be given something.",
  receipt: "A printed slip that proves a purchase or payment was made.",
  neighbor: "A person who lives next door or nearby.",
  weigh: "To find out how heavy something is.",
  watermelon: "A large fruit with a hard green rind and juicy red flesh.",
  flashlight: "A small, portable electric light powered by batteries.",
  thunderstorm: "A storm with thunder, lightning, and usually heavy rain.",
  skateboard: "A narrow board on wheels that a person rides while standing.",
  earthquake: "A sudden, violent shaking of the ground caused by movement of the earth's crust.",
  backpack: "A bag with straps, carried on the back to hold belongings.",
  rainbow: "An arc of colors that appears in the sky when sunlight shines through rain.",
  snowflake: "A single small ice crystal that falls as snow.",
  firefly: "A small flying beetle that glows in the dark.",
  sunflower: "A tall plant with large yellow petals around a dark center.",
  teammate: "A person who plays on the same team as you.",
  haircut: "The act or style of cutting someone's hair.",
  lighthouse: "A tower with a bright light that warns or guides ships near the coast.",
  playground: "An outdoor area with equipment for children to play on.",
  sandbox: "A low container or pit filled with sand for children to play in.",
  footprint: "The mark left by a foot or shoe on a surface.",
  rowboat: "A small boat moved through the water using oars.",
  sailboat: "A boat that is moved by the wind pushing against its sails.",
  airplane: "A powered aircraft with wings that flies through the air.",
  airport: "A place where aircraft take off, land, and where passengers board.",
  recharge: "To fill a battery with power again, or to restore energy.",
  review: "To look over or study something again, often to check or remember it.",
  return: "To go back to a place, or to give something back.",
  replace: "To put a new or different thing in the place of another.",
  rewrite: "To write something again, usually to improve it.",
  misplace: "To put something in the wrong place and be unable to find it.",
  mistaken: "Wrong about something; having an incorrect belief.",
  mislead: "To give someone a false idea or impression, often unintentionally.",
  misbehave: "To behave badly.",
  misspell: "To spell a word incorrectly.",
  unable: "Not having the power, skill, or means to do something.",
  unwrapped: "Took the wrapping or covering off of something.",
  unfair: "Not treating people equally or justly.",
  unequal: "Not the same in size, amount, or value.",
  unhappy: "Feeling sad rather than glad.",
  careless: "Not giving enough care or attention; likely to make mistakes.",
  fearless: "Having no fear; brave.",
  hopeless: "Having or showing no hope.",
  helpless: "Unable to take care of or defend oneself.",
  harmless: "Not able or likely to cause damage or injury.",
  happier: "More glad or pleased (comparative of happy).",
  heavier: "Having more weight (comparative of heavy).",
  strongest: "Having the most physical power (superlative of strong).",
  fastest: "Moving or able to move at the greatest speed (superlative of fast).",
  quickest: "Taking the least amount of time (superlative of quick).",
  middle: "The point or part that is halfway between two ends or sides.",
  simple: "Easy to understand or do; not complicated.",
  candle: "A stick of wax with a wick in the center that is burned to give light.",
  battle: "A fight between two armies or opposing sides.",
  uncle: "The brother of one's mother or father, or the husband of one's aunt.",
  towel: "A piece of absorbent cloth used for drying the body after bathing.",
  travel: "To go from one place to another, especially over a long distance.",
  barrel: "A large, round container with curved sides, usually made of wood or metal.",
  camel: "A large desert animal with one or two humps on its back, used for carrying loads.",
  squirrel: "A small animal with a long bushy tail that climbs trees and gathers nuts.",
  doctor: "A person trained and licensed to treat sick or injured people.",
  actor: "A person who performs in plays, movies, or television shows.",
  sailor: "A person who works as a member of a ship's crew.",
  visitor: "A person who comes to see a place or another person for a short time.",
  author: "A person who writes a book, article, or other written work.",
  teacher: "A person whose job is to help students learn.",
  worker: "A person who does a job, especially physical or manual labor.",
  player: "A person who takes part in a game or sport.",
  writer: "A person who writes books, stories, or articles.",
  driver: "A person who operates or steers a vehicle.",
  bargain: "Something bought or sold at a good, low price.",
  certain: "Sure about something, without any doubt.",
  except: "Leaving out or not including something or someone.",
  government: "The group of people with the authority to run a country, state, or city.",
  latitude: "The distance of a place north or south of the equator, measured in imaginary lines that circle the globe.",
  longitude: "The distance of a place east or west, measured by imaginary lines that run from the North Pole to the South Pole.",
  compass: "A tool with a needle that always points north, used for finding direction.",
  parallel: "Lines or surfaces that run side by side, always staying the same distance apart and never meeting.",
  recommend: "To suggest that something is good or suitable.",
  bicycle: "A two-wheeled vehicle that you ride by pedaling.",
  abrupt: "Sudden and unexpected.",
  absence: "The state of being away or not present.",
  accident: "An unexpected and unintended event, often causing harm.",
  accomplish: "To succeed in finishing or achieving something.",
  account: "A description or report of an event, or a record kept of money.",
  achieve: "To successfully reach a goal through effort or skill.",
  across: "From one side of something to the other.",
  activity: "Something that is done for enjoyment or as part of a task.",
  adjust: "To change something slightly to make it fit or work better.",
  adopt: "To take a child or animal into your family and raise it as your own; or, to begin using a new idea or method.",
  advantage: "Something that puts you in a better or more favorable position.",
  advice: "A suggestion or recommendation about what someone should do.",
  against: "In opposition to, or touching and leaning on.",
  agree: "To have the same opinion as someone else, or to say yes to something.",
  ahead: "In front, or further forward in space, time, or progress.",
  alarm: "A sound, device, or signal that warns of danger or wakes someone up.",
  alley: "A narrow passage or lane between or behind buildings.",
  alphabet: "The set of letters used to write a language, arranged in a fixed order.",
  already: "Before now, or sooner than expected.",
  always: "At all times; every time, without exception.",
  amount: "A quantity of something.",
  anchor: "A heavy metal device dropped from a ship to keep it from drifting.",
  ancient: "Very old, from a long time ago.",
  anger: "A strong feeling of annoyance or displeasure.",
  angle: "The space between two lines or surfaces that meet at a point, measured in degrees.",
  animal: "A living creature, other than a plant, that can move and feel.",
  ankle: "The joint connecting the foot to the leg.",
  announce: "To make something known publicly.",
  anxious: "Feeling worried or nervous about what might happen.",
  apology: "A statement saying you are sorry for doing something wrong.",
  appear: "To become visible or come into sight.",
  applaud: "To clap one's hands to show approval.",
  apple: "A round fruit with red, green, or yellow skin and firm white flesh.",
  apron: "A piece of clothing worn over the front of the body to protect clothes while cooking or working.",
  area: "A particular part or space within a place, or the size of a surface.",
  argue: "To express disagreement, often with strong feelings.",
  arrive: "To reach a destination or place.",
  artist: "A person who creates art, such as painting, drawing, or music.",
  asleep: "In a state of sleep.",
  assist: "To help someone do something.",
  astronaut: "A person trained to travel and work in space.",
  athlete: "A person who is trained in or skilled at sports or physical exercise.",
  attempt: "An effort to do something, especially something difficult; or, to try to do something.",
  attend: "To be present at an event or place.",
  attention: "Careful focus or notice given to something.",
  attract: "To cause someone or something to come closer or take interest.",
  audience: "A group of people gathered to watch or listen to a performance.",
  august: "The eighth month of the year.",
  aunt: "The sister of one's mother or father, or the wife of one's uncle.",
  autumn: "The season between summer and winter when leaves fall; also called fall.",
  average: "A typical or usual amount, found by adding values together and dividing by how many there are.",
  awake: "Not asleep.",
  award: "A prize given for an achievement.",
  aware: "Having knowledge or realization of something.",
  awesome: "Causing feelings of great admiration or amazement.",
  awful: "Very bad or unpleasant.",
  awkward: "Causing or feeling embarrassment, discomfort, or a lack of ease; not graceful.",
  baggage: "Bags and suitcases packed for traveling.",
  bakery: "A shop where bread, cakes, and pastries are made and sold.",
  balance: "To keep steady without falling by evenly spreading weight; or, a steady state in which weight is spread evenly.",
  balloon: "A small rubber bag that is filled with air or gas until it expands.",
  banana: "A long curved fruit with soft sweet flesh and a yellow peel.",
  bandage: "A strip of material used to wrap and protect a wound.",
  banish: "To send someone away from a place, usually as punishment.",
  banter: "Light, playful teasing or joking conversation.",
  barely: "Only just; almost not.",
  baron: "A nobleman of a rank just below a viscount.",
  basement: "The floor of a building that is below ground level.",
  basket: "A container made of woven material, used for holding or carrying things.",
  bathe: "To wash one's body, usually in a bathtub.",
  battery: "A device that stores and supplies electrical power.",
  beast: "A large or dangerous animal.",
  beetle: "An insect with a hard, shiny pair of wing covers.",
  before: "Earlier than a particular time or event.",
  beggar: "A person who lives by asking others for money or food.",
  beginner: "A person who is just starting to learn or do something.",
  behave: "To act in a particular way, especially in a proper or acceptable manner.",
  behind: "At or toward the back of something.",
  belief: "A feeling that something is true or real, even without proof.",
  belong: "To be the property of, or to be a member of a group.",
  beneath: "In a lower position than something else; underneath.",
  benefit: "An advantage or helpful effect gained from something.",
  berry: "A small, round, juicy fruit without a pit.",
  between: "In the space or time separating two things.",
  beyond: "On the far side of, or further than, something.",
  billion: "The number 1,000,000,000; a thousand million.",
  blanket: "A large piece of soft cloth used as a cover for warmth.",
  bleed: "To lose blood from the body, usually from a wound.",
  blender: "A kitchen appliance that mixes or purees food using a spinning blade.",
  blizzard: "A severe snowstorm with strong winds.",
  blossom: "To produce flowers, or to grow and develop; also, a flower, especially one that grows on a tree or bush.",
  blouse: "A loose-fitting shirt worn by women or girls.",
  blueberry: "A small, round, dark blue berry that grows on a bush.",
  blunder: "A careless or stupid mistake.",
  blush: "To become red in the face, usually from embarrassment.",
  board: "A long, flat piece of wood or other material.",
  boast: "To talk with too much pride about one's own achievements.",
  body: "The whole physical structure of a person or animal.",
  boil: "To heat a liquid until it bubbles and turns to steam.",
  bold: "Confident and willing to take risks; also describes thick, heavy print or lines that stand out clearly.",
  bolt: "A metal pin or rod, often with a nut, used to fasten things together.",
  bomb: "A weapon designed to explode and cause damage.",
  bond: "A close connection or relationship between people, or something that joins things together.",
  bone: "One of the hard parts that make up the skeleton of a body.",
  bonnet: "A soft hat tied under the chin, often worn by babies.",
  bonus: "An extra reward or amount given in addition to what is expected.",
  bookcase: "A piece of furniture with shelves for holding books.",
  boomerang: "A curved piece of wood that can be thrown so that it returns to the thrower.",
  border: "The line that separates two areas, countries, or regions.",
  bore: "To make someone feel uninterested or tired by being dull.",
  boring: "Not interesting; causing a person to feel tired or restless.",
  borrow: "To take and use something with the intention of returning it.",
  boss: "A person who is in charge of and gives orders to others at work.",
  bother: "To cause someone trouble, worry, or annoyance.",
  bottle: "A container, usually made of glass or plastic, used for holding liquids.",
  bottom: "The lowest part or point of something.",
  bound: "A leap or jump; also describes something tied firmly, or certain to happen.",
  boundary: "A line that marks the limit or edge of an area.",
  bouquet: "A bunch of flowers arranged together, often as a gift.",
  bow: "A knot tied with two or more loops, often made from ribbon, used as a decoration; also, to bend the body forward, or a weapon used to shoot arrows.",
  bowl: "A round, deep dish used for holding food or liquid.",
  boxer: "A person who fights in the sport of boxing.",
  brain: "The organ inside the head that controls thought, memory, and feeling.",
  brake: "A device used to slow down or stop a moving vehicle.",
  branch: "A part of a tree that grows out from the trunk.",
  brand: "A particular kind or make of product, identified by a name or symbol.",
  brave: "Showing courage; not afraid to face danger or pain.",
  bravery: "Courageous behavior in the face of danger or fear.",
  bread: "A food made from flour, water, and yeast that is baked.",
  break: "To cause something to separate into pieces, often suddenly.",
  breakfast: "The first meal of the day, eaten in the morning.",
  breast: "The front upper part of the chest.",
  breath: "The air taken into or let out of the lungs.",
  breathe: "To take air into the lungs and let it out again.",
  breeze: "A light, gentle wind.",
  bribe: "To offer someone money or a gift to dishonestly persuade them to do something; or, the money or gift offered.",
  brick: "A rectangular block of baked clay used for building.",
  bride: "A woman who is about to be married or who has just been married.",
  brief: "Lasting only a short time; short.",
  bright: "Giving off or filled with a lot of light; also, very smart.",
  brilliant: "Extremely bright, or extremely intelligent or skillful.",
  brisk: "Quick and energetic.",
  broad: "Large in width or extent, or covering a wide range.",
  broccoli: "A green vegetable with a thick stalk and clusters of small flower buds.",
  broil: "To cook food directly under or over high heat.",
  broken: "Damaged and separated into pieces, or no longer working.",
  bronze: "A brownish metal made by mixing copper and tin.",
  brooch: "A piece of jewelry fastened to clothing with a pin.",
  brook: "A small, natural stream of water.",
  broom: "A brush with a long handle, used for sweeping floors.",
  brother: "A boy or man with the same parents as another person.",
  brow: "The forehead, or the ridge of hair above the eye.",
  brown: "A color like that of coffee or soil, made by mixing red, yellow, and black.",
  bruise: "An injury that discolors the skin without breaking it, caused by a hit or fall.",
  brush: "A tool with bristles, used for cleaning, painting, or grooming; or, to clean or smooth something using such a tool.",
  brutal: "Extremely harsh, cruel, or violent.",
  bubble: "A thin ball of liquid filled with air or gas.",
  bucket: "A round, open container with a handle, used for carrying liquids.",
  buckle: "A fastener, usually metal, used to join two ends of a belt or strap.",
  bud: "A small swelling on a plant that develops into a leaf, flower, or shoot.",
  budget: "A plan for how to spend a certain amount of money.",
  buffalo: "A large, heavily built wild ox with curved horns.",
  buffet: "A meal set out on a table where guests serve themselves.",
  buggy: "A small, light carriage or cart, often pushed for a baby.",
  bugle: "A brass instrument similar to a small trumpet, often used in the military.",
  build: "To make something by putting parts or materials together.",
  builder: "A person whose job is to construct buildings.",
  building: "A structure with walls and a roof, such as a house or school.",
  bulb: "The glass part of an electric lamp that gives off light, or the round underground part of certain plants.",
  bulge: "A rounded shape that swells outward from a surface.",
  bull: "An adult male of cattle.",
  bullet: "A small piece of metal shot from a gun.",
  bully: "A person who uses strength or power to frighten or hurt someone weaker; or, to intentionally scare or hurt someone weaker.",
  bump: "A small lump or raised area on a surface; also, a light knock or collision, or to knock into something.",
  bumper: "A bar attached to the front or back of a vehicle to protect it in a collision.",
  bunch: "A group of things growing or fastened together.",
  bundle: "A number of things tied or wrapped together.",
  bungalow: "A small house, usually with only one story.",
  bunk: "A narrow bed, often one of a stacked pair.",
  bunny: "A small rabbit.",
  burden: "A heavy load that is carried, or something difficult that must be dealt with.",
  bureau: "A chest of drawers for storing clothes, or a government department.",
  burglar: "A person who breaks into a building to steal.",
  burial: "The act of placing a dead body into the ground.",
  burn: "To be on fire, or to damage something with fire or heat.",
  burner: "The part of a stove that produces heat for cooking.",
  burrow: "A hole or tunnel dug in the ground by an animal to live in.",
  burst: "To break open or apart suddenly, often with force.",
  bury: "To put something in the ground and cover it with earth.",
  bus: "A large motor vehicle that carries many passengers.",
  bush: "A woody plant smaller than a tree, with many branches.",
  bushel: "A unit for measuring dry goods like fruit or grain.",
  business: "The activity of buying and selling goods or services to make money.",
  busy: "Having a lot to do; not free or idle.",
  butcher: "A person whose job is to cut and sell meat.",
  butter: "A soft, yellow food made from churned cream.",
  butterfly: "An insect with large, often colorful wings.",
  button: "A small disk used to fasten clothing, or a part that is pressed to operate a machine.",
  calendar: "A chart showing the days, weeks, and months of a year.",
  camera: "A device used to take photographs or record video.",
  campground: "An area set aside for camping.",
  special: "Better, different, or more important than what is usual.",
  field: "A large open area of land, often used for growing crops or playing sports.",
  friend: "A person you know well and like, who is not a relative.",
  chief: "A person with the highest rank or authority in a group.",
  piece: "A part or portion of something larger.",
  thief: "A person who steals.",
  grief: "Deep sorrow, especially caused by someone's death.",
  shield: "A flat piece of metal or other material carried for protection against attack.",
  relief: "A feeling of comfort after the end of pain, worry, or distress.",
  yield: "To give way or surrender, or to produce a crop or result.",
  fierce: "Showing strong, aggressive force or intensity.",
  pierce: "To make a hole in something with a sharp point.",
  niece: "The daughter of one's brother or sister.",
  official: "A person who holds a position of authority, such as a referee or government worker; or, something approved by an authority.",
  social: "Relating to activities in which people spend time together.",
  crucial: "Extremely important; necessary for something to happen.",
  financial: "Relating to money or how it is managed.",
  partial: "Existing only in part; not complete.",
  martial: "Relating to fighting or war, as in martial arts.",
  captain: "The leader of a team, or the person in charge of a ship or aircraft.",
  curtain: "A piece of fabric hung to cover a window or to separate spaces.",
  fountain: "A structure that shoots water into the air, often for decoration.",
  villain: "A wicked person, especially one who is the main bad character in a story.",
  complaint: "A statement that something is unsatisfactory or unacceptable.",
  material: "The substance from which something is made, such as cloth or wood.",
  serial: "Happening in a series, one after another, such as a story published in parts.",
  dial: "A circular control, such as on a clock or radio, used to select a setting.",
  trial: "A test to try something out, or a formal examination of evidence in a court.",
  giant: "A being in stories that is much larger than a normal person.",
  radiant: "Shining brightly, or showing happiness clearly.",
  complacent: "Feeling so satisfied that you stop trying or fail to notice problems.",
  patient: "Able to wait calmly without getting upset; also, a person receiving medical care.",
  efficient: "Working well without wasting time, effort, or resources.",
  sufficient: "Enough for a particular purpose.",
  weight: "How heavy something is; also, a heavy object, especially one used for exercise or to hold something in place.",
  freight: "Goods transported by truck, train, ship, or plane.",
  eight: "The number 8.",
  sleigh: "A vehicle on runners, used for traveling over snow, often pulled by animals.",
  vein: "A blood vessel that carries blood toward the heart.",
  reindeer: "A large deer with antlers that lives in cold northern regions.",
};
