// Example sentences for the "Use in a Sentence" button.
// Keyed by lowercase word so lookups are case-insensitive.
// Add an entry here whenever you add a word to words.js, or the
// button falls back to a generic sentence for that word.
const SENTENCES = {
  scratch: "The cat left a scratch on the wooden post.",
  stream: "We waded through the cool stream behind the house.",
  strong: "The weightlifter has very strong arms.",
  thread: "She used blue thread to sew the button.",
  throat: "My throat feels sore after singing all day.",
  spring: "Flowers begin to bloom in the spring.",
  scream: "She let out a loud scream on the roller coaster.",
  screen: "The movie played on a giant screen.",
  spread: "Spread the peanut butter evenly on the bread.",
  squeak: "The old door let out a tiny squeak.",
  sketch: "He made a quick sketch of the mountain.",
  pitch: "The pitcher threw a fast pitch over the plate.",
  catch: "Try to catch the ball with both hands.",
  badge: "The police officer wore a shiny badge.",
  wedge: "He used a wedge to split the log.",
  fudge: "Grandma made chocolate fudge for dessert.",
  judge: "The judge listened carefully before deciding the case.",
  ridge: "We hiked along the rocky ridge at sunset.",
  bridge: "The cars drove slowly across the bridge.",
  edge: "Be careful standing near the edge of the cliff.",
  coach: "The coach taught us a new soccer drill.",
  toast: "She had toast and jam for breakfast.",
  roast: "We had a roast chicken for dinner.",
  coast: "The lighthouse stands along the rocky coast.",
  floating: "The leaf was floating gently on the pond.",
  knight: "The knight raised his sword to defend the castle.",
  knock: "Please knock before you open the door.",
  knee: "He scraped his knee while riding his bike.",
  kneel: "The player will kneel to tie his shoelace.",
  know: "Do you know the answer to this riddle?",
  wrist: "She wore a bracelet around her wrist.",
  write: "Please write your name at the top of the page.",
  wrong: "That math answer is wrong; try it again.",
  wreck: "The old car was a total wreck after the storm.",
  wrap: "Can you wrap this gift before the party?",
  gnat: "A tiny gnat buzzed around the porch light.",
  gnaw: "The puppy loves to gnaw on its chew toy.",
  sign: "She painted a sign that said 'Welcome Home.'",
  design: "The artist sketched a new design for the mural.",
  assignment: "I finished my homework assignment before dinner.",
  honest: "He gave an honest answer about what happened.",
  honor: "The firefighter received an honor for her bravery.",
  hour: "We waited almost an hour for the bus.",
  ghost: "The campers told a scary ghost story by the fire.",
  ghastly: "The haunted house had a ghastly green glow.",
  echo: "Her voice made an echo in the empty cave.",
  chore: "Taking out the trash is my least favorite chore.",
  chase: "The dog loves to chase squirrels in the yard.",
  choose: "You may choose any flavor of ice cream.",
  choice: "Picking a pet was a hard choice to make.",
  beautiful: "The sunset painted the sky with beautiful colors.",
  laughter: "The room filled with laughter after the joke.",
  daughter: "My daughter starts third grade this fall.",
  caught: "The goalie caught the ball just in time.",
  taught: "Our teacher taught us how to multiply fractions.",
  bought: "She bought a new backpack for school.",
  brought: "He brought cookies to share with the class.",
  thought: "I thought the test would be harder than it was.",
  voyage: "The sailors set off on a long voyage across the ocean.",
  destroyer: "The navy destroyer sailed past the harbor.",
  annoy: "Loud chewing tends to annoy my brother.",
  employ: "The bakery plans to employ two new workers.",
  ground: "The acorn fell and rolled across the ground.",
  bounce: "The ball will bounce if you drop it hard.",
  mountain: "We hiked to the top of the snowy mountain.",
  voice: "She has a soft, gentle voice.",
  noise: "A loud noise woke up the whole house.",
  avoid: "Try to avoid the puddles on your way to school.",
  moisture: "The towel absorbed the moisture from the floor.",
  ceiling: "A spider crawled across the ceiling.",
  receive: "You will receive your grade tomorrow.",
  receipt: "Keep your receipt in case you need to return it.",
  neighbor: "Our neighbor waved to us from across the street.",
  weigh: "Please weigh the apples before you buy them.",
  watermelon: "We sliced a juicy watermelon for the picnic.",
  flashlight: "He used a flashlight to find his way in the dark.",
  thunderstorm: "A thunderstorm rolled in just before dinner.",
  skateboard: "She rode her skateboard down the smooth sidewalk.",
  earthquake: "The earthquake shook the dishes off the shelf.",
  backpack: "He packed his lunch inside his backpack.",
  rainbow: "A rainbow appeared after the rain stopped.",
  snowflake: "Each snowflake has its own unique pattern.",
  firefly: "A single firefly blinked near the garden.",
  sunflower: "The sunflower turned to face the morning light.",
  teammate: "She passed the ball to her teammate.",
  haircut: "He got a short haircut before school started.",
  lighthouse: "The lighthouse beam swept across the dark water.",
  playground: "The kids ran straight to the playground at recess.",
  sandbox: "The toddler built a castle in the sandbox.",
  footprint: "We found a muddy footprint on the porch.",
  rowboat: "They paddled the rowboat across the calm lake.",
  sailboat: "The sailboat glided across the bay.",
  airplane: "The airplane climbed high above the clouds.",
  airport: "We arrived at the airport two hours early.",
  recharge: "Don't forget to recharge your tablet overnight.",
  review: "Let's review the spelling words before the quiz.",
  return: "Please return the library book by Friday.",
  replace: "We need to replace the broken light bulb.",
  rewrite: "She had to rewrite her essay after the first draft.",
  misplace: "Try not to misplace your house key again.",
  mistaken: "I was mistaken about the time of the game.",
  mislead: "The foggy directions could mislead a new driver.",
  misbehave: "The puppy tends to misbehave when it's left alone.",
  misspell: "It's easy to misspell a tricky word like this one.",
  unable: "She was unable to find her missing shoe.",
  unwrapped: "He unwrapped the present as fast as he could.",
  unfair: "It felt unfair that practice got cancelled twice.",
  unequal: "The two teams had an unequal number of players.",
  unhappy: "The baby looked unhappy after dropping his toy.",
  careless: "A careless mistake cost her the spelling bee.",
  fearless: "The firefighter looked fearless climbing the tall ladder.",
  hopeless: "The puzzle seemed hopeless until she found the last piece.",
  helpless: "The kitten looked helpless stuck up in the tree.",
  harmless: "The garden snake is small and harmless.",
  happier: "She felt happier after talking to her friend.",
  heavier: "The suitcase felt heavier than I expected.",
  strongest: "The strongest player carried the equipment bag.",
  fastest: "He is the fastest runner on the team.",
  quickest: "Find the quickest way to solve this problem.",
  middle: "She sat in the middle seat of the row.",
  simple: "The recipe only needs a few simple steps.",
  candle: "We lit a candle for the birthday cake.",
  battle: "The two knights had a pretend sword battle.",
  uncle: "My uncle taught me how to fish.",
  towel: "Grab a towel after you finish swimming.",
  travel: "We plan to travel to the mountains this summer.",
  barrel: "The pickles were stored in a wooden barrel.",
  camel: "The camel walked slowly across the desert sand.",
  squirrel: "A squirrel buried an acorn under the tree.",
  doctor: "The doctor checked my heartbeat at the appointment.",
  actor: "The actor forgot his lines during the play.",
  sailor: "The sailor tied a strong knot on the dock.",
  visitor: "We had a surprise visitor at the front door.",
  author: "The author signed copies of her new book.",
  teacher: "Our teacher gave us extra credit for reading.",
  worker: "Each worker wore a bright safety vest.",
  player: "The star player scored the winning point.",
  writer: "The writer spent all morning on one chapter.",
  driver: "The bus driver waved as we got on.",
  bargain: "She found a great bargain on winter boots.",
  certain: "I am certain the meeting starts at noon.",
  except: "Everyone finished the race except one runner.",
  government: "The government built a new bridge downtown.",
  latitude: "Lines of latitude run east and west on a map.",
  longitude: "Lines of longitude run north and south on a map.",
  compass: "He used a compass to find which way was north.",
  parallel: "The two roads run parallel to each other.",
  recommend: "Can you recommend a good book to read?",
  bicycle: "She rode her bicycle to the park.",
  abrupt: "The movie had an abrupt ending that surprised everyone.",
  absence: "His absence from practice was due to a cold.",
  accident: "It was an accident, not something she meant to do.",
  accomplish: "She worked hard to accomplish her reading goal.",
  account: "He keeps a detailed account of his savings.",
  achieve: "Practice every day to achieve your best score.",
  across: "A turtle slowly crawled across the road.",
  activity: "Building a model volcano was our science activity.",
  adjust: "Please adjust your chair so you can reach the desk.",
  adopt: "Our family plans to adopt a shelter dog.",
  advantage: "Being tall gave her an advantage in basketball.",
  advice: "My grandmother gave me good advice about studying.",
  against: "The team played against their toughest rival.",
  agree: "We all agree that pizza night is the best night.",
  ahead: "She finished her project ahead of schedule.",
  alarm: "The alarm rang loudly at six in the morning.",
  alley: "The cat slipped quietly down the narrow alley.",
  alphabet: "She can already say the whole alphabet.",
  already: "He had already finished his homework before dinner.",
  always: "She always packs an extra pencil in her bag.",
  amount: "What amount of sugar does the recipe need?",
  anchor: "The sailors dropped the anchor near the shore.",
  ancient: "The museum displayed an ancient Egyptian vase.",
  anger: "He took a deep breath to calm his anger.",
  angle: "Measure the angle of the triangle with a protractor.",
  animal: "Which animal would you choose as a pet?",
  ankle: "She twisted her ankle jumping off the swing.",
  announce: "The principal will announce the winners at lunch.",
  anxious: "She felt anxious before her first piano recital.",
  apology: "He wrote an apology note after breaking the vase.",
  appear: "Stars begin to appear once the sky gets dark.",
  applaud: "The crowd began to applaud after the song ended.",
  apple: "She packed an apple in her lunch box.",
  apron: "Dad wore an apron while flipping pancakes.",
  area: "The picnic area had several wooden tables.",
  argue: "The siblings began to argue over the last cookie.",
  arrive: "We should arrive at the airport by noon.",
  artist: "The young artist painted a colorful mural.",
  asleep: "The baby fell asleep during the car ride.",
  assist: "Can you assist me with carrying these boxes?",
  astronaut: "The astronaut floated weightlessly inside the spacecraft.",
  athlete: "The young athlete trained every morning before school.",
  attempt: "She made another attempt to solve the puzzle.",
  attend: "We plan to attend the school concert tonight.",
  attention: "Please pay attention while the teacher explains the rule.",
  attract: "Bright flowers attract butterflies to the garden.",
  audience: "The audience clapped loudly after the show.",
  august: "School usually starts in late August.",
  aunt: "My aunt sent me a postcard from her trip.",
  autumn: "The leaves turn orange and red in autumn.",
  average: "She scored above average on the math quiz.",
  awake: "He was wide awake long before his alarm went off.",
  award: "She received an award for perfect attendance.",
  aware: "Be aware of cars before you cross the street.",
  awesome: "That magic trick was absolutely awesome.",
  awful: "The weather turned awful right before the game.",
  awkward: "He felt awkward walking into the room late.",
  baggage: "We loaded the baggage onto the airplane.",
  bakery: "The bakery smelled like fresh bread and cinnamon.",
  balance: "She tried to balance on one foot during yoga.",
  balloon: "The red balloon floated up into the sky.",
  banana: "He sliced a banana onto his cereal.",
  bandage: "Mom put a bandage on my scraped knee.",
  banish: "The king threatened to banish the dishonest knight.",
  banter: "The two friends traded playful banter at lunch.",
  barely: "She barely made it to school before the bell rang.",
  baron: "The wealthy baron owned a huge castle.",
  basement: "We store the holiday decorations in the basement.",
  basket: "She filled the basket with fresh strawberries.",
  bathe: "It's time to bathe the dog before dinner.",
  battery: "The flashlight needs a new battery.",
  beast: "The story described a friendly beast who guarded the forest.",
  beetle: "A shiny black beetle crawled across the leaf.",
  before: "Wash your hands before you eat lunch.",
  beggar: "In the old story, a beggar asked for bread.",
  beginner: "She is still a beginner at playing the violin.",
  behave: "The puppy promised to behave during the car ride.",
  behind: "He hid behind the curtain during the game.",
  belief: "Her belief in herself helped her finish the race.",
  belong: "These mittens belong to my little sister.",
  beneath: "The treasure was buried beneath the old oak tree.",
  benefit: "Eating vegetables has many benefits for your health.",
  berry: "She picked a juicy berry from the bush.",
  between: "The cat squeezed between the fence posts.",
  beyond: "The trail continues far beyond those hills.",
  billion: "There are more than a billion stars in the galaxy.",
  blanket: "She wrapped herself in a warm blanket.",
  bleed: "A small scrape on his knee began to bleed.",
  blender: "Mom used the blender to make a smoothie.",
  blizzard: "The blizzard buried the street in snow.",
  blossom: "The cherry tree will blossom in early spring.",
  blouse: "She wore a white blouse to the school picture day.",
  blueberry: "He picked a ripe blueberry from the bush.",
  blunder: "Forgetting his lines was an embarrassing blunder.",
  blush: "She began to blush when everyone clapped for her.",
  board: "We nailed a wooden board across the broken fence.",
  boast: "He likes to boast about winning the race.",
  body: "Stretching keeps your body flexible and strong.",
  boil: "Watch the water boil before adding the noodles.",
  bold: "The headline was printed in big, bold letters.",
  bolt: "He tightened the loose bolt with a wrench.",
  bomb: "The movie showed a robot defusing a bomb.",
  bond: "The two puppies formed a close bond.",
  bone: "The dog buried its bone under the porch.",
  bonnet: "The baby wore a soft bonnet to keep warm.",
  bonus: "She earned a bonus sticker for finishing early.",
  bookcase: "He stacked his comics on the tall bookcase.",
  boomerang: "The boomerang spun through the air and came right back.",
  border: "The fence marks the border between the two yards.",
  bore: "The long car ride started to bore the kids.",
  boring: "He thought the museum tour was a little boring.",
  borrow: "Can I borrow your eraser for a minute?",
  boss: "Her boss praised her for finishing the project early.",
  bother: "Sorry to bother you, but I have a quick question.",
  bottle: "She filled her water bottle before practice.",
  bottom: "The treasure chest sat at the bottom of the lake.",
  bound: "The rabbit took one big bound over the fence.",
  boundary: "The painted line marks the boundary of the field.",
  bouquet: "He picked a small bouquet of wildflowers.",
  bow: "She tied a pink bow on top of the gift box.",
  bowl: "Pour the cereal into a clean bowl.",
  boxer: "The boxer trained hard before the big match.",
  brain: "Reading every day is good exercise for your brain.",
  brake: "She pressed the brake to stop her bicycle in time.",
  branch: "A bird landed on the highest branch.",
  brand: "He recognized the brand on the cereal box.",
  brave: "The brave firefighter ran into the burning building.",
  bravery: "She was given a medal for her bravery.",
  bread: "He toasted two slices of bread for breakfast.",
  break: "Be careful not to break the glass ornament.",
  breakfast: "We ate pancakes for breakfast this morning.",
  breast: "The robin had a bright orange breast.",
  breath: "He took a deep breath before diving into the pool.",
  breathe: "Remember to breathe slowly when you feel nervous.",
  breeze: "A cool breeze drifted through the open window.",
  bribe: "He tried to bribe his sister with candy.",
  brick: "The old house was built from red brick.",
  bride: "The bride wore a long white dress.",
  brief: "She gave a brief answer before running to class.",
  bright: "The bright sun made it hard to see the screen.",
  brilliant: "That was a brilliant idea for the science project.",
  brisk: "We took a brisk walk before it got dark.",
  broad: "The river has a broad, sandy shore.",
  broccoli: "He hid a piece of broccoli under his napkin.",
  broil: "Mom set the oven to broil the vegetables.",
  broken: "The broken vase lay in pieces on the floor.",
  bronze: "She won a bronze medal in the swim meet.",
  brooch: "Grandma pinned a sparkling brooch to her coat.",
  brook: "A small brook trickled through the quiet woods.",
  broom: "He swept the kitchen floor with a broom.",
  brother: "My older brother taught me how to ride a bike.",
  brow: "Sweat dripped down his brow during the race.",
  brown: "The puppy has soft brown fur.",
  bruise: "She got a small bruise after falling off her scooter.",
  brush: "Don't forget to brush your teeth before bed.",
  brutal: "The desert heat felt brutal during the afternoon hike.",
  bubble: "She blew a giant bubble with her gum.",
  bucket: "He filled the bucket with sand at the beach.",
  buckle: "She fastened the buckle on her bike helmet.",
  bud: "A tiny green bud appeared on the rose bush.",
  budget: "We made a budget for the class field trip.",
  buffalo: "A herd of buffalo grazed across the prairie.",
  buffet: "The restaurant offered a breakfast buffet.",
  buggy: "The baby slept inside the buggy at the park.",
  bugle: "The soldier played a tune on his bugle.",
  build: "The kids worked together to build a sandcastle.",
  builder: "The builder measured twice before cutting the wood.",
  building: "Our school is the tallest building on the block.",
  bulb: "Screw the new light bulb into the lamp.",
  bulge: "His backpack had a strange bulge from the textbooks.",
  bull: "The bull grazed quietly in the green pasture.",
  bullet: "The museum displayed an old bullet from the war.",
  bully: "It's never okay to let someone bully a classmate.",
  bump: "The car hit a small bump in the road.",
  bumper: "The truck's bumper was dented in the parking lot.",
  bunch: "She picked a bunch of grapes for snack time.",
  bundle: "He carried a bundle of firewood to the porch.",
  bungalow: "They rented a small bungalow near the beach.",
  bunk: "My little brother sleeps on the top bunk.",
  bunny: "The bunny hopped quickly across the yard.",
  burden: "Carrying the heavy backpack felt like a burden.",
  bureau: "She keeps her socks in the top drawer of the bureau.",
  burglar: "The alarm scared the burglar away from the house.",
  burial: "The pirates marked the spot of the treasure's burial.",
  burn: "Be careful not to burn the popcorn.",
  burner: "She turned off the stove burner after cooking.",
  burrow: "The rabbit dug a burrow under the fence.",
  burst: "The balloon burst with a loud pop.",
  bury: "The dog likes to bury its bones in the yard.",
  bus: "We rode the yellow school bus to the museum.",
  bush: "A rabbit hopped out from behind the bush.",
  bushel: "They picked a whole bushel of apples.",
  business: "She started a small business selling friendship bracelets.",
  busy: "The kitchen was busy with cooks before the big dinner.",
  butcher: "The butcher wrapped the meat in white paper.",
  butter: "Spread the butter evenly on the warm toast.",
  butterfly: "A bright orange butterfly landed on the flower.",
  button: "She lost a button off her favorite coat.",
  calendar: "He circled the date on the kitchen calendar.",
  camera: "She brought her camera to take pictures at the zoo.",
  campground: "We pitched our tent at the campground by the lake.",
  special: "Today is a special day because it's her birthday.",
  field: "The players ran out onto the soccer field.",
  friend: "She invited her best friend to the sleepover.",
  chief: "The fire chief led the team into the building.",
  piece: "She ate one more piece of the pizza.",
  thief: "The thief slipped quietly out the back window.",
  grief: "The whole town shared in their grief after the loss.",
  shield: "The knight raised his shield to block the arrow.",
  relief: "She felt relief once the test was finally over.",
  yield: "The driver had to yield to the oncoming traffic.",
  fierce: "The tiger gave a fierce, loud roar.",
  pierce: "The needle can pierce through thick fabric.",
  niece: "My niece is visiting us this weekend.",
  official: "The official blew the whistle to start the game.",
  social: "She enjoys social activities like clubs and team sports.",
  crucial: "Sleep is crucial before a big test.",
  financial: "The class learned about financial planning and saving money.",
  partial: "He gave only a partial answer to the question.",
  martial: "She takes martial arts classes on Tuesdays.",
  captain: "The team voted her to be team captain.",
  curtain: "She pulled the curtain closed before bed.",
  fountain: "Coins glittered at the bottom of the fountain.",
  villain: "The villain in the movie wore a long black cape.",
  complaint: "He filed a complaint about the broken swing.",
  material: "The dress was made from soft, silky material.",
  serial: "She reads one chapter of the serial story every night.",
  dial: "Turn the dial to set the oven temperature.",
  trial: "The new product went through a careful trial.",
  giant: "The giant in the story lived at the top of the beanstalk.",
  radiant: "The bride had a radiant smile on her wedding day.",
  complacent: "Winning the first game made the team feel complacent.",
  patient: "Please be patient while we wait for the bus.",
  efficient: "The new dishwasher is more efficient than the old one.",
  sufficient: "One slice of pizza wasn't sufficient for his hunger.",
  weight: "He lifted a heavy weight at the gym.",
  freight: "The freight train carried boxes across the country.",
  eight: "She is turning eight years old next week.",
  sleigh: "Santa's sleigh is pulled by eight reindeer.",
  vein: "The doctor found a vein in her arm.",
  reindeer: "A reindeer pulled the sled across the snow.",
};
