// Example sentences for the "Use in a Sentence" button.
// Keyed by lowercase word so lookups are case-insensitive.
// Add an entry here whenever you add a word to words.js, or the
// button falls back to a generic sentence for that word.
const SENTENCES = {
  scratch: "The cat left a scratch on the wooden post.",
  stream: "We waded through the cool stream behind the house.",
  strong: "The weightlifter has very strong arms.",
  thread: "She used blue thread to sew the button.",
  throat: "My throat feels sore after singing all day.",
  spring: "Flowers begin to bloom in the spring.",
  scream: "She let out a loud scream on the roller coaster.",
  screen: "The movie played on a giant screen.",
  spread: "Spread the peanut butter evenly on the bread.",
  squeak: "The old door let out a tiny squeak.",
  sketch: "He made a quick sketch of the mountain.",
  pitch: "The pitcher threw a fast pitch over the plate.",
  catch: "Try to catch the ball with both hands.",
  badge: "The police officer wore a shiny badge.",
  wedge: "He used a wedge to split the log.",
  fudge: "Grandma made chocolate fudge for dessert.",
  judge: "The judge listened carefully before deciding the case.",
  ridge: "We hiked along the rocky ridge at sunset.",
  bridge: "The cars drove slowly across the bridge.",
  edge: "Be careful standing near the edge of the cliff.",
  coach: "The coach taught us a new soccer drill.",
  toast: "She had toast and jam for breakfast.",
  roast: "We had a roast chicken for dinner.",
  coast: "The lighthouse stands along the rocky coast.",
  floating: "The leaf was floating gently on the pond.",
  knight: "The knight raised his sword to defend the castle.",
  knock: "Please knock before you open the door.",
  knee: "He scraped his knee while riding his bike.",
  kneel: "The player will kneel to tie his shoelace.",
  know: "Do you know the answer to this riddle?",
  wrist: "She wore a bracelet around her wrist.",
  write: "Please write your name at the top of the page.",
  wrong: "That math answer is wrong; try it again.",
  wreck: "The old car was a total wreck after the storm.",
  wrap: "Can you wrap this gift before the party?",
  gnat: "A tiny gnat buzzed around the porch light.",
  gnaw: "The puppy loves to gnaw on its chew toy.",
  sign: "She painted a sign that said 'Welcome Home.'",
  design: "The artist sketched a new design for the mural.",
  assignment: "I finished my homework assignment before dinner.",
  honest: "He gave an honest answer about what happened.",
  honor: "The firefighter received an honor for her bravery.",
  hour: "We waited almost an hour for the bus.",
  ghost: "The campers told a scary ghost story by the fire.",
  ghastly: "The haunted house had a ghastly green glow.",
  echo: "Her voice made an echo in the empty cave.",
  chore: "Taking out the trash is my least favorite chore.",
  chase: "The dog loves to chase squirrels in the yard.",
  choose: "You may choose any flavor of ice cream.",
  choice: "Picking a pet was a hard choice to make.",
  beautiful: "The sunset painted the sky with beautiful colors.",
  laughter: "The room filled with laughter after the joke.",
  daughter: "My daughter starts third grade this fall.",
  caught: "The goalie caught the ball just in time.",
  taught: "Our teacher taught us how to multiply fractions.",
  bought: "She bought a new backpack for school.",
  brought: "He brought cookies to share with the class.",
  thought: "I thought the test would be harder than it was.",
  voyage: "The sailors set off on a long voyage across the ocean.",
  destroyer: "The navy destroyer sailed past the harbor.",
  annoy: "Loud chewing tends to annoy my brother.",
  employ: "The bakery plans to employ two new workers.",
  ground: "The acorn fell and rolled across the ground.",
  bounce: "The ball will bounce if you drop it hard.",
  mountain: "We hiked to the top of the snowy mountain.",
  voice: "She has a soft, gentle voice.",
  noise: "A loud noise woke up the whole house.",
  avoid: "Try to avoid the puddles on your way to school.",
  moisture: "The towel absorbed the moisture from the floor.",
  ceiling: "A spider crawled across the ceiling.",
  receive: "You will receive your grade tomorrow.",
  receipt: "Keep your receipt in case you need to return it.",
  neighbor: "Our neighbor waved to us from across the street.",
  weigh: "Please weigh the apples before you buy them.",
  watermelon: "We sliced a juicy watermelon for the picnic.",
  flashlight: "He used a flashlight to find his way in the dark.",
  thunderstorm: "A thunderstorm rolled in just before dinner.",
  skateboard: "She rode her skateboard down the smooth sidewalk.",
  earthquake: "The earthquake shook the dishes off the shelf.",
  backpack: "He packed his lunch inside his backpack.",
  rainbow: "A rainbow appeared after the rain stopped.",
  snowflake: "Each snowflake has its own unique pattern.",
  firefly: "A single firefly blinked near the garden.",
  sunflower: "The sunflower turned to face the morning light.",
  teammate: "She passed the ball to her teammate.",
  haircut: "He got a short haircut before school started.",
  lighthouse: "The lighthouse beam swept across the dark water.",
  playground: "The kids ran straight to the playground at recess.",
  sandbox: "The toddler built a castle in the sandbox.",
  footprint: "We found a muddy footprint on the porch.",
  rowboat: "They paddled the rowboat across the calm lake.",
  sailboat: "The sailboat glided across the bay.",
  airplane: "The airplane climbed high above the clouds.",
  airport: "We arrived at the airport two hours early.",
  recharge: "Don't forget to recharge your tablet overnight.",
  review: "Let's review the spelling words before the quiz.",
  return: "Please return the library book by Friday.",
  replace: "We need to replace the broken light bulb.",
  rewrite: "She had to rewrite her essay after the first draft.",
  misplace: "Try not to misplace your house key again.",
  mistaken: "I was mistaken about the time of the game.",
  mislead: "The foggy directions could mislead a new driver.",
  misbehave: "The puppy tends to misbehave when it's left alone.",
  misspell: "It's easy to misspell a tricky word like this one.",
  unable: "She was unable to find her missing shoe.",
  unwrapped: "He unwrapped the present as fast as he could.",
  unfair: "It felt unfair that practice got cancelled twice.",
  unequal: "The two teams had an unequal number of players.",
  unhappy: "The baby looked unhappy after dropping his toy.",
  careless: "A careless mistake cost her the spelling bee.",
  fearless: "The firefighter looked fearless climbing the tall ladder.",
  hopeless: "The puzzle seemed hopeless until she found the last piece.",
  helpless: "The kitten looked helpless stuck up in the tree.",
  harmless: "The garden snake is small and harmless.",
  happier: "She felt happier after talking to her friend.",
  heavier: "The suitcase felt heavier than I expected.",
  strongest: "The strongest player carried the equipment bag.",
  fastest: "He is the fastest runner on the team.",
  quickest: "Find the quickest way to solve this problem.",
  middle: "She sat in the middle seat of the row.",
  simple: "The recipe only needs a few simple steps.",
  candle: "We lit a candle for the birthday cake.",
  battle: "The two knights had a pretend sword battle.",
  uncle: "My uncle taught me how to fish.",
  towel: "Grab a towel after you finish swimming.",
  travel: "We plan to travel to the mountains this summer.",
  barrel: "The pickles were stored in a wooden barrel.",
  camel: "The camel walked slowly across the desert sand.",
  squirrel: "A squirrel buried an acorn under the tree.",
  doctor: "The doctor checked my heartbeat at the appointment.",
  actor: "The actor forgot his lines during the play.",
  sailor: "The sailor tied a strong knot on the dock.",
  visitor: "We had a surprise visitor at the front door.",
  author: "The author signed copies of her new book.",
  teacher: "Our teacher gave us extra credit for reading.",
  worker: "Each worker wore a bright safety vest.",
  player: "The star player scored the winning point.",
  writer: "The writer spent all morning on one chapter.",
  driver: "The bus driver waved as we got on.",
  bargain: "She found a great bargain on winter boots.",
  certain: "I am certain the meeting starts at noon.",
  except: "Everyone finished the race except one runner.",
  government: "The government built a new bridge downtown.",
  latitude: "Lines of latitude run east and west on a map.",
  longitude: "Lines of longitude run north and south on a map.",
  compass: "He used a compass to find which way was north.",
  parallel: "The two roads run parallel to each other.",
  recommend: "Can you recommend a good book to read?",
  bicycle: "She rode her bicycle to the park.",
  abrupt: "The movie had an abrupt ending that surprised everyone.",
  absence: "His absence from practice was due to a cold.",
  accident: "It was an accident, not something she meant to do.",
  accomplish: "She worked hard to accomplish her reading goal.",
  account: "He keeps a detailed account of his savings.",
  achieve: "Practice every day to achieve your best score.",
  across: "A turtle slowly crawled across the road.",
  activity: "Building a model volcano was our science activity.",
  adjust: "Please adjust your chair so you can reach the desk.",
  adopt: "Our family plans to adopt a shelter dog.",
  advantage: "Being tall gave her an advantage in basketball.",
  advice: "My grandmother gave me good advice about studying.",
  against: "The team played against their toughest rival.",
  agree: "We all agree that pizza night is the best night.",
  ahead: "She finished her project ahead of schedule.",
  alarm: "The alarm rang loudly at six in the morning.",
  alley: "The cat slipped quietly down the narrow alley.",
  alphabet: "She can already say the whole alphabet.",
  already: "He had already finished his homework before dinner.",
  always: "She always packs an extra pencil in her bag.",
  amount: "What amount of sugar does the recipe need?",
  anchor: "The sailors dropped the anchor near the shore.",
  ancient: "The museum displayed an ancient Egyptian vase.",
  anger: "He took a deep breath to calm his anger.",
  angle: "Measure the angle of the triangle with a protractor.",
  animal: "Which animal would you choose as a pet?",
  ankle: "She twisted her ankle jumping off the swing.",
  announce: "The principal will announce the winners at lunch.",
  anxious: "She felt anxious before her first piano recital.",
  apology: "He wrote an apology note after breaking the vase.",
  appear: "Stars begin to appear once the sky gets dark.",
  applaud: "The crowd began to applaud after the song ended.",
  apple: "She packed an apple in her lunch box.",
  apron: "Dad wore an apron while flipping pancakes.",
  area: "The picnic area had several wooden tables.",
  argue: "The siblings began to argue over the last cookie.",
  arrive: "We should arrive at the airport by noon.",
  artist: "The young artist painted a colorful mural.",
  asleep: "The baby fell asleep during the car ride.",
  assist: "Can you assist me with carrying these boxes?",
  astronaut: "The astronaut floated weightlessly inside the spacecraft.",
  athlete: "The young athlete trained every morning before school.",
  attempt: "She made another attempt to solve the puzzle.",
  attend: "We plan to attend the school concert tonight.",
  attention: "Please pay attention while the teacher explains the rule.",
  attract: "Bright flowers attract butterflies to the garden.",
  audience: "The audience clapped loudly after the show.",
  august: "School usually starts in late August.",
  aunt: "My aunt sent me a postcard from her trip.",
  autumn: "The leaves turn orange and red in autumn.",
  average: "She scored above average on the math quiz.",
  awake: "He was wide awake long before his alarm went off.",
  award: "She received an award for perfect attendance.",
  aware: "Be aware of cars before you cross the street.",
  awesome: "That magic trick was absolutely awesome.",
  awful: "The weather turned awful right before the game.",
  awkward: "He felt awkward walking into the room late.",
  baggage: "We loaded the baggage onto the airplane.",
  bakery: "The bakery smelled like fresh bread and cinnamon.",
  balance: "She tried to balance on one foot during yoga.",
  balloon: "The red balloon floated up into the sky.",
  banana: "He sliced a banana onto his cereal.",
  bandage: "Mom put a bandage on my scraped knee.",
  banish: "The king threatened to banish the dishonest knight.",
  banter: "The two friends traded playful banter at lunch.",
  barely: "She barely made it to school before the bell rang.",
  baron: "The wealthy baron owned a huge castle.",
  basement: "We store the holiday decorations in the basement.",
  basket: "She filled the basket with fresh strawberries.",
  bathe: "It's time to bathe the dog before dinner.",
  battery: "The flashlight needs a new battery.",
  beast: "The story described a friendly beast who guarded the forest.",
  beetle: "A shiny black beetle crawled across the leaf.",
  before: "Wash your hands before you eat lunch.",
  beggar: "In the old story, a beggar asked for bread.",
  beginner: "She is still a beginner at playing the violin.",
  behave: "The puppy promised to behave during the car ride.",
  behind: "He hid behind the curtain during the game.",
  belief: "Her belief in herself helped her finish the race.",
  belong: "These mittens belong to my little sister.",
  beneath: "The treasure was buried beneath the old oak tree.",
  benefit: "Eating vegetables has many benefits for your health.",
  berry: "She picked a juicy berry from the bush.",
  between: "The cat squeezed between the fence posts.",
  beyond: "The trail continues far beyond those hills.",
  billion: "There are more than a billion stars in the galaxy.",
  blanket: "She wrapped herself in a warm blanket.",
  bleed: "A small scrape on his knee began to bleed.",
  blender: "Mom used the blender to make a smoothie.",
  blizzard: "The blizzard buried the street in snow.",
  blossom: "The cherry tree will blossom in early spring.",
  blouse: "She wore a white blouse to the school picture day.",
  blueberry: "He picked a ripe blueberry from the bush.",
  blunder: "Forgetting his lines was an embarrassing blunder.",
  blush: "She began to blush when everyone clapped for her.",
  board: "We nailed a wooden board across the broken fence.",
  boast: "He likes to boast about winning the race.",
  body: "Stretching keeps your body flexible and strong.",
  boil: "Watch the water boil before adding the noodles.",
  bold: "The headline was printed in big, bold letters.",
  bolt: "He tightened the loose bolt with a wrench.",
  bomb: "The movie showed a robot defusing a bomb.",
  bond: "The two puppies formed a close bond.",
  bone: "The dog buried its bone under the porch.",
  bonnet: "The baby wore a soft bonnet to keep warm.",
  bonus: "She earned a bonus sticker for finishing early.",
  bookcase: "He stacked his comics on the tall bookcase.",
  boomerang: "The boomerang spun through the air and came right back.",
  border: "The fence marks the border between the two yards.",
  bore: "The long car ride started to bore the kids.",
  boring: "He thought the museum tour was a little boring.",
  borrow: "Can I borrow your eraser for a minute?",
  boss: "Her boss praised her for finishing the project early.",
  bother: "Sorry to bother you, but I have a quick question.",
  bottle: "She filled her water bottle before practice.",
  bottom: "The treasure chest sat at the bottom of the lake.",
  bound: "The rabbit took one big bound over the fence.",
  boundary: "The painted line marks the boundary of the field.",
  bouquet: "He picked a small bouquet of wildflowers.",
  bow: "She tied a pink bow on top of the gift box.",
  bowl: "Pour the cereal into a clean bowl.",
  boxer: "The boxer trained hard before the big match.",
  brain: "Reading every day is good exercise for your brain.",
  brake: "She pressed the brake to stop her bicycle in time.",
  branch: "A bird landed on the highest branch.",
  brand: "He recognized the brand on the cereal box.",
  brave: "The brave firefighter ran into the burning building.",
  bravery: "She was given a medal for her bravery.",
  bread: "He toasted two slices of bread for breakfast.",
  break: "Be careful not to break the glass ornament.",
  breakfast: "We ate pancakes for breakfast this morning.",
  breast: "The robin had a bright orange breast.",
  breath: "He took a deep breath before diving into the pool.",
  breathe: "Remember to breathe slowly when you feel nervous.",
  breeze: "A cool breeze drifted through the open window.",
  bribe: "He tried to bribe his sister with candy.",
  brick: "The old house was built from red brick.",
  bride: "The bride wore a long white dress.",
  brief: "She gave a brief answer before running to class.",
  bright: "The bright sun made it hard to see the screen.",
  brilliant: "That was a brilliant idea for the science project.",
  brisk: "We took a brisk walk before it got dark.",
  broad: "The river has a broad, sandy shore.",
  broccoli: "He hid a piece of broccoli under his napkin.",
  broil: "Mom set the oven to broil the vegetables.",
  broken: "The broken vase lay in pieces on the floor.",
  bronze: "She won a bronze medal in the swim meet.",
  brooch: "Grandma pinned a sparkling brooch to her coat.",
  brook: "A small brook trickled through the quiet woods.",
  broom: "He swept the kitchen floor with a broom.",
  brother: "My older brother taught me how to ride a bike.",
  brow: "Sweat dripped down his brow during the race.",
  brown: "The puppy has soft brown fur.",
  bruise: "She got a small bruise after falling off her scooter.",
  brush: "Don't forget to brush your teeth before bed.",
  brutal: "The desert heat felt brutal during the afternoon hike.",
  bubble: "She blew a giant bubble with her gum.",
  bucket: "He filled the bucket with sand at the beach.",
  buckle: "She fastened the buckle on her bike helmet.",
  bud: "A tiny green bud appeared on the rose bush.",
  budget: "We made a budget for the class field trip.",
  buffalo: "A herd of buffalo grazed across the prairie.",
  buffet: "The restaurant offered a breakfast buffet.",
  buggy: "The baby slept inside the buggy at the park.",
  bugle: "The soldier played a tune on his bugle.",
  build: "The kids worked together to build a sandcastle.",
  builder: "The builder measured twice before cutting the wood.",
  building: "Our school is the tallest building on the block.",
  bulb: "Screw the new light bulb into the lamp.",
  bulge: "His backpack had a strange bulge from the textbooks.",
  bull: "The bull grazed quietly in the green pasture.",
  bullet: "The museum displayed an old bullet from the war.",
  bully: "It's never okay to let someone bully a classmate.",
  bump: "The car hit a small bump in the road.",
  bumper: "The truck's bumper was dented in the parking lot.",
  bunch: "She picked a bunch of grapes for snack time.",
  bundle: "He carried a bundle of firewood to the porch.",
  bungalow: "They rented a small bungalow near the beach.",
  bunk: "My little brother sleeps on the top bunk.",
  bunny: "The bunny hopped quickly across the yard.",
  burden: "Carrying the heavy backpack felt like a burden.",
  bureau: "She keeps her socks in the top drawer of the bureau.",
  burglar: "The alarm scared the burglar away from the house.",
  burial: "The pirates marked the spot of the treasure's burial.",
  burn: "Be careful not to burn the popcorn.",
  burner: "She turned off the stove burner after cooking.",
  burrow: "The rabbit dug a burrow under the fence.",
  burst: "The balloon burst with a loud pop.",
  bury: "The dog likes to bury its bones in the yard.",
  bus: "We rode the yellow school bus to the museum.",
  bush: "A rabbit hopped out from behind the bush.",
  bushel: "They picked a whole bushel of apples.",
  business: "She started a small business selling friendship bracelets.",
  busy: "The kitchen was busy with cooks before the big dinner.",
  butcher: "The butcher wrapped the meat in white paper.",
  butter: "Spread the butter evenly on the warm toast.",
  butterfly: "A bright orange butterfly landed on the flower.",
  button: "She lost a button off her favorite coat.",
  calendar: "He circled the date on the kitchen calendar.",
  camera: "She brought her camera to take pictures at the zoo.",
  campground: "We pitched our tent at the campground by the lake.",
  special: "Today is a special day because it's her birthday.",
  field: "The players ran out onto the soccer field.",
  friend: "She invited her best friend to the sleepover.",
  chief: "The fire chief led the team into the building.",
  piece: "She ate one more piece of the pizza.",
  thief: "The thief slipped quietly out the back window.",
  grief: "The whole town shared in their grief after the loss.",
  shield: "The knight raised his shield to block the arrow.",
  relief: "She felt relief once the test was finally over.",
  yield: "The driver had to yield to the oncoming traffic.",
  fierce: "The tiger gave a fierce, loud roar.",
  pierce: "The needle can pierce through thick fabric.",
  niece: "My niece is visiting us this weekend.",
  official: "The official blew the whistle to start the game.",
  social: "She enjoys social activities like clubs and team sports.",
  crucial: "Sleep is crucial before a big test.",
  financial: "The class learned about financial planning and saving money.",
  partial: "He gave only a partial answer to the question.",
  martial: "She takes martial arts classes on Tuesdays.",
  captain: "The team voted her to be team captain.",
  curtain: "She pulled the curtain closed before bed.",
  fountain: "Coins glittered at the bottom of the fountain.",
  villain: "The villain in the movie wore a long black cape.",
  complaint: "He filed a complaint about the broken swing.",
  material: "The dress was made from soft, silky material.",
  serial: "She reads one chapter of the serial story every night.",
  dial: "Turn the dial to set the oven temperature.",
  trial: "The new product went through a careful trial.",
  giant: "The giant in the story lived at the top of the beanstalk.",
  radiant: "The bride had a radiant smile on her wedding day.",
  complacent: "Winning the first game made the team feel complacent.",
  patient: "Please be patient while we wait for the bus.",
  efficient: "The new dishwasher is more efficient than the old one.",
  sufficient: "One slice of pizza wasn't sufficient for his hunger.",
  weight: "He lifted a heavy weight at the gym.",
  freight: "The freight train carried boxes across the country.",
  eight: "She is turning eight years old next week.",
  sleigh: "Santa's sleigh is pulled by eight reindeer.",
  vein: "The doctor found a vein in her arm.",
  reindeer: "A reindeer pulled the sled across the snow.",
  abandon: "They had to abandon the old house after the storm.",
  ability: "She has the ability to solve math problems quickly.",
  abolish: "The school decided to abolish the uniform policy.",
  absorb: "Sponges absorb water very efficiently.",
  abundant: "The garden provided an abundant harvest of tomatoes.",
  academic: "He received an award for his academic achievements.",
  accent: "She spoke English with a noticeable French accent.",
  accept: "He was happy to accept the invitation to the party.",
  accompany: "My dog likes to accompany me on my morning walks.",
  accurate: "The scientist needed accurate measurements for the experiment.",
  accuse: "Do not accuse him of stealing without proof.",
  acid: "Lemon juice contains a mild form of acid.",
  acquire: "I want to acquire a new book for my collection.",
  action: "The superhero sprang into action to save the city.",
  active: "He leads an active lifestyle by playing sports daily.",
  actual: "The actual cost was lower than the estimate.",
  adapt: "Animals adapt to their environment to survive winter.",
  addition: "The new porch is a wonderful addition to our home.",
  address: "Please write your home address on this form.",
  adequate: "The student gave an adequate explanation for being late.",
  admire: "I admire the artist for her creative paintings.",
  admit: "He had to admit that he broke the window.",
  advance: "The army began to advance across the field.",
  adventure: "Camping in the mountains was a wild adventure.",
  advertise: "Companies advertise on television to reach more customers.",
  advise: "Doctors advise people to eat a balanced diet.",
  advocate: "She loves to advocate for cleaner city parks.",
  affect: "The loud music will affect your ability to study.",
  afford: "I cannot afford to buy that expensive jacket.",
  afraid: "The little boy was afraid of the dark.",
  agency: "The travel agency booked our flights to Europe.",
  agenda: "The principal handed out the agenda for the meeting.",
  agent: "The secret agent went on a dangerous mission.",
  aggressive: "The aggressive dog barked loudly at the mail carrier.",
  agriculture: "The region's economy relies heavily on agriculture.",
  aid: "The charity provides aid to families in need.",
  aim: "You must aim carefully to hit the bullseye.",
  aircraft: "The massive aircraft landed safely on the runway.",
  airline: "We booked our tickets with a popular airline.",
  ballot: "Each citizen cast their ballot in the election box.",
  banner: "A large welcome banner hung across the school entrance.",
  barren: "The desert looked barren and empty of life.",
  barrier: "The security barrier stopped cars from entering.",
  basic: "Reading is a basic skill everyone needs to learn.",
  basis: "Trust is the true basis of any good friendship.",
  beach: "We built sandcastles on the beach all afternoon.",
  beacon: "The lighthouse served as a beacon for ships.",
  beauty: "The sunset over the ocean was a thing of pure beauty.",
  become: "Caterpillars eventually become beautiful butterflies.",
  begin: "The concert will begin in exactly ten minutes.",
  behavior: "Her polite behavior impressed the school principal.",
  believe: "I believe that it will rain later today.",
  besides: "Besides apples, what other fruits do you like?",
  betray: "He promised never to betray his best friend's secret.",
  bias: "The umpire showed bias toward the home team.",
  biography: "I read an interesting biography about Abraham Lincoln.",
  biology: "In biology class, we learned how plants grow.",
  birth: "The family celebrated the birth of a baby girl.",
  biscuit: "She ate a warm biscuit with butter for breakfast.",
  bitter: "The dark chocolate tasted quite bitter to the child.",
  blame: "Do not blame others for your own mistakes.",
  blast: "We could hear the loud blast from miles away.",
  blend: "You need to blend the ingredients to make a smoothie.",
  blind: "The blind man navigated the streets with a guide dog.",
  block: "The child stacked one wooden block on top of another.",
  boiler: "The building's central boiler broke down during the winter.",
  cabin: "They stayed in a cozy log cabin in the woods.",
  cable: "The heavy bridge was supported by steel cable systems.",
  cactus: "A lone cactus grew in the dry desert soil.",
  cage: "The bird flew happily out of its open cage.",
  calamity: "The massive earthquake was a terrible calamity for the town.",
  calculate: "Use your calculator to calculate the total cost.",
  calm: "Take deep breaths to stay calm during the test.",
  camp: "We set up our summer camp near the rushing river.",
  campaign: "He ran a successful campaign to become class president.",
  campus: "The college campus was beautiful in the autumn.",
  canal: "Boats traveled slowly down the narrow canal.",
  cancel: "They had to cancel the game due to heavy rain.",
  cancer: "Medical researchers work hard to find a cure for cancer.",
  candidate: "She is a strong candidate for the student council position.",
  canvas: "The artist painted a beautiful landscape on the canvas.",
  canyon: "We looked down into the vast depth of the canyon.",
  capable: "I am completely capable of finishing this project myself.",
  capacity: "The stadium was filled to its maximum capacity.",
  capital: "Washington, D.C. is the capital of the United States.",
  capture: "The soldiers managed to capture the enemy fortress.",
  carbon: "Diamond and graphite are both made of pure carbon.",
  career: "She wants to pursue a career in scientific research.",
  careful: "Be careful when walking across the icy sidewalk.",
  cargo: "The large container ship carried cargo across the ocean.",
  carol: "The choir sang a joyful holiday carol for the audience.",
  carpet: "We spilled juice on the living room carpet.",
  carriage: "The princess arrived in a beautiful horse-drawn carriage.",
  carrot: "The rabbit happily chewed on a crunchy orange carrot.",
  carry: "Please help me carry these heavy grocery bags inside.",
  carton: "Don't forget to buy a carton of milk today.",
  carve: "He likes to carve small wooden animals as a hobby.",
  cascade: "Water began to cascade down the rock wall.",
  case: "In this specific case, the rules do not apply.",
  cash: "I paid for the movie ticket using cash.",
  castle: "The medieval castle stood high upon the hill.",
  casual: "He wore casual clothes like jeans and a t-shirt.",
  catalog: "I flipped through the clothing catalog to find a jacket.",
  category: "Group these objects by their size category.",
  cattle: "The herd of cattle grazed quietly in the field.",
  cause: "High winds were the primary cause of the power outage.",
  caution: "Proceed with caution when driving through thick fog.",
  cautious: "The cautious cat crept slowly toward the squeaking toy.",
  cave: "They explored a dark limestone cave on their vacation.",
  cavity: "The dentist found a small cavity in my tooth.",
  cease: "The loud drilling noises will cease at five o'clock.",
  damage: "The storm caused severe damage to the neighborhood trees.",
  danger: "The warning sign warned hikers of the danger ahead.",
  dangerous: "It is dangerous to cross the street without looking both ways.",
  darkness: "The flashlight cut through the thick darkness of night.",
  darling: "My grandmother calls me her favorite little darling.",
  dash: "I had to dash to the bus stop so I wouldn't miss it.",
  database: "The library database stores the titles of all books.",
  dawn: "The birds began singing at the first light of dawn.",
  daylight: "It is much safer to hike while there is still daylight.",
  debate: "The debate team argued points for and against the law.",
  debris: "Workers cleared the architectural debris after the old building fell.",
  decade: "Technology has changed immensely over the past decade.",
  decay: "Sugar can cause teeth to undergo rapid decay.",
  deceive: "Do not try to deceive your teacher with a fake excuse.",
  decide: "You must decide which flavor of ice cream you want.",
  decision: "Choosing a college is an incredibly important decision.",
  declare: "The president will declare a new national holiday tomorrow.",
  decline: "I had to decline the offer because I was too busy.",
  decorate: "We like to decorate the house for winter parties.",
  decrease: "Turning down the radio will decrease the volume level.",
  dedicate: "Teachers dedicate their lives to helping students learn.",
  deduct: "Stores deduct discount amounts at the cash register.",
  deed: "Helping the elderly woman cross the street was a good deed.",
  deep: "The divers swam deep into the cold blue ocean.",
  defeat: "Our team managed to defeat our rivals in the finals.",
  defend: "Castle walls were built to defend against attacking forces.",
  defense: "A strong defense prevented the other team from scoring points.",
  defiance: "The student shook his head in defiance of the teacher's order.",
  define: "Use a dictionary to define words you don't know.",
  definite: "We have a definite plan to meet at noon.",
  degree: "The water temperature dropped by one degree Celsius.",
  delay: "Bad weather will delay our flight by three hours.",
  delegate: "Each state sent a delegate to the national convention.",
  deliberate: "Breaking the vase was a deliberate act of mischief.",
  delicate: "The glass sculpture was far too delicate to touch.",
  delicious: "My mother baked a delicious apple pie for dessert.",
  delight: "The children cheered with delight when they saw the snow.",
  deliver: "Mail carriers deliver packages to our house every afternoon.",
  delivery: "We are waiting on a food delivery from the local diner.",
  demand: "The workers made a firm demand for safer conditions.",
  democracy: "Citizens vote in a democracy to choose leaders.",
  demolish: "The construction crew will demolish the old stadium.",
  demon: "The scary story featured an ancient demon in a cave.",
  demonstrate: "The teacher will demonstrate how to perform the experiment.",
  denial: "His denial of the crime didn't convince the judge.",
  denounce: "The community leaders met to denounce the local violence.",
  dense: "We got lost in the dense fog along the highway.",
  density: "Wood has a lower density than a solid steel block.",
  dental: "Regular dental checkups prevent painful cavities from forming.",
  eager: "The eager students raised their hands to answer the question.",
  eagle: "A majestic eagle soared high above the mountaintops.",
  early: "Waking up early allows you to see the beautiful sunrise.",
  earn: "You can earn money by mowing lawns on weekends.",
  earnest: "He made an earnest effort to apologize for his mistake.",
  earth: "From space, Earth looks like a beautiful blue marble.",
  ease: "She completed the difficult obstacle course with total ease.",
  easily: "The tall basketball player could easily reach the high hoop.",
  east: "The compass pointed directly toward the east coast line.",
  eastern: "They live in the eastern part of the large state.",
  easy: "The vocabulary test was surprisingly easy for the class.",
  eclipse: "We wore special glasses to view the solar eclipse.",
  ecology: "Studying ecology helps us understand how ecosystems stay balanced.",
  economic: "The country is experiencing a period of positive economic growth.",
  economy: "Tourism is an essential part of the local island economy.",
  edition: "I bought the latest edition of the science textbook.",
  editor: "The newspaper editor assigned the big story to a reporter.",
  educate: "Schools aim to educate children and prepare them for life.",
  education: "A good education opens up many wonderful job opportunities.",
  effect: "The medicine had an immediate calming effect on the patient.",
  effective: "Wearing a mask is an effective way to prevent illness.",
  efficiency: "The factory upgraded its machinery to increase working efficiency.",
  effort: "It takes real effort to learn how to play an instrument.",
  either: "You can choose either the chocolate cake or vanilla ice cream.",
  elaborate: "They built an elaborate maze out of cardboard boxes.",
  elastic: "The elastic waistband made the sweatpants very comfortable to wear.",
  elbow: "He scraped his elbow when he fell off his skateboard.",
  elder: "It is important to listen to the wisdom of an elder.",
  elect: "The citizens gathered to elect their new town mayor.",
  election: "The school held an election for student council president.",
  electric: "Our family decided to purchase an electric car to save fuel.",
  electricity: "The storm knocked out the electricity across the entire city.",
  elegant: "She wore an elegant gown to the formal dinner party.",
  element: "Practice is a key element of mastering any new sport.",
  elementary: "The concepts taught in elementary school form your foundation.",
  elephant: "The elephant sprayed water over its back using its trunk.",
  elevate: "You should elevate your foot if you sprain your ankle.",
  elevator: "We took the elevator to the tenth floor of the building.",
  eligible: "You must be eighteen years old to be eligible to vote.",
  eliminate: "Healthy eating can help eliminate toxic substances from your body.",
  elite: "The elite athletes trained for years to make the Olympic team.",
  eloquent: "The speaker delivered an eloquent address that inspired everyone present.",
  elsewhere: "If the store is closed, we will have to shop elsewhere.",
  elusive: "The rare butterfly proved to be very elusive to the researchers.",
  embargo: "The government lifted the trade embargo after peace talks succeeded.",
  embark: "Tomorrow, we will embark on a great adventure across the country.",
  fabric: "The soft fabric of the shirt felt nice against my skin.",
  fabulous: "She did a fabulous job on her history class presentation.",
  face: "A big smile lit up his face when he won.",
  facility: "The new sports facility has an indoor swimming pool.",
  fact: "It is a scientific fact that water freezes at zero degrees.",
  factor: "Hard work was the main factor in her artistic success.",
  factory: "The local car factory employs hundreds of people from town.",
  faculty: "The school faculty met to discuss the upcoming winter dance.",
  fade: "The bright paint will fade if exposed to direct sunlight.",
  failure: "Failure is just an opportunity to try again more intelligently.",
  faint: "We heard a faint sound coming from the dark attic.",
  fair: "The teacher made sure to give everyone a fair turn.",
  faith: "Have faith in your abilities when taking the difficult test.",
  faithful: "The faithful dog sat waiting by the door for its owner.",
  maintain: "We must maintain our bicycles so they do not rust.",
  majority: "The majority of the students voted to go on a field trip.",
  malice: "She felt no malice toward the person who accidentally bumped into her.",
  mammal: "A whale is a mammal, not a fish.",
  mandatory: "Wearing a helmet is mandatory when riding a scooter.",
  maneuver: "The driver made a quick maneuver to avoid the pothole.",
  manifest: "His joy became manifest when he started dancing.",
  manipulate: "You can manipulate the puppet using these strings.",
  manner: "She answered the phone in a polite manner.",
  manuscript: "The author sent her manuscript to the publisher.",
  marathon: "He trained for months to run the city marathon.",
  margin: "Please write your name in the top margin of the paper.",
  marvel: "We stopped to marvel at the beautiful sunset.",
  mascot: "Our school mascot is a fierce tiger.",
  massive: "The workers moved a massive boulder out of the road.",
  masterpiece: "The artist spent years painting his masterpiece.",
  mature: "He showed a mature attitude by admitting his mistake.",
  maximum: "The maximum capacity of the elevator is ten people.",
  meadow: "Wildflowers grew everywhere in the open meadow.",
  measure: "Use a ruler to measure the length of the string.",
  mechanic: "The mechanic fixed our car's engine.",
  media: "The news media covered the entire election.",
  mediate: "The teacher tried to mediate the argument between the friends.",
  medicinal: "Some plants have medicinal qualities that soothe pain.",
  medieval: "The history class studied medieval castles.",
  mediocre: "The food was mediocre, but the service was excellent.",
  melancholy: "The rainy weather put her in a melancholy mood.",
  melody: "She hummed a cheerful melody while cleaning.",
  memorable: "Our trip to the Grand Canyon was highly memorable.",
  menace: "The loose dog was a menace to the neighborhood.",
  mention: "Did you mention the party to your sister?",
  mentor: "The high school coach acted as a mentor to the player.",
  merchant: "The merchant sold rugs at the market.",
  mercy: "The king showed mercy and spared the prisoner.",
  mere: "It is a mere scratch, so you do not need a bandage.",
  merge: "The two lanes merge into one up ahead.",
  merit: "The project has a lot of merit and deserves a good grade.",
  metaphor: "Saying \"time is money\" is a common metaphor.",
  method: "Scientists use a strict method to run experiments.",
  meticulous: "He was meticulous about keeping his desk organized.",
  microscope: "We looked at plant cells under the microscope.",
  migration: "The bird migration happens every autumn.",
  mild: "We enjoyed the mild weather during our spring walk.",
  mimic: "The parrot can mimic human voices perfectly.",
  minimum: "The minimum age to ride the roller coaster is twelve.",
  minuscule: "There was a minuscule bug crawling on the leaf.",
  miracle: "It was a miracle that nobody got hurt in the crash.",
  mischief: "The puppy caused a lot of mischief by chewing the shoes.",
  miserable: "He felt miserable when he had the flu.",
  misfortune: "It was a misfortune that it rained on our picnic day.",
  mission: "The astronauts successfully completed their space mission.",
  mixture: "The cake batter is a mixture of flour, sugar, and eggs.",
  mobilize: "The community began to mobilize to clean up the park.",
  model: "He built a plastic model of an airplane.",
  moderate: "The hike was of moderate difficulty, so anyone could do it.",
  modest: "Despite winning the race, she remained modest.",
  modify: "You need to modify your essay to fix the errors.",
  molecule: "A water molecule is made of hydrogen and oxygen.",
  momentum: "The sled gained momentum as it slid down the hill.",
  monarch: "The monarch ruled the country for fifty years.",
  monitor: "The teacher will monitor the students during the test.",
  monopoly: "The massive company held a monopoly on electricity.",
  monotonous: "Sorting papers all day is a monotonous task.",
  monument: "We visited the monument dedicated to the soldiers.",
  morale: "Winning the game boosted the team's morale.",
  mortal: "Human beings are mortal, unlike the mythical gods.",
  motivate: "Good grades motivate students to study hard.",
  motive: "The detective looked for a motive for the crime.",
  mourn: "The family gathered to mourn the loss of their grandfather.",
  multiple: "She had multiple reasons for leaving the party early.",
  multitude: "A multitude of fans waited outside the concert hall.",
  municipal: "The municipal building houses the mayor's office.",
  murmur: "He spoke in a low murmur so no one else could hear.",
  muscle: "Lifting weights helps build arm muscle.",
  mutual: "The two friends shared a mutual respect for each other.",
  myriad: "There is a myriad of stars in the night sky.",
  mysterious: "A mysterious package arrived at our doorstep.",
  myth: "The teacher explained the ancient Greek myth of Zeus.",
  naive: "He was naive to think that the project would be easy.",
  narrative: "The novel has a thrilling narrative.",
  narrow: "The car squeezed through the narrow alleyway.",
  nasal: "The cold gave him a stuffy, nasal voice.",
  native: "Kangaroos are native to Australia.",
  natural: "Floods are a type of natural disaster.",
  nausea: "The bumpy boat ride caused him severe nausea.",
  navigate: "We used a map to navigate through the city.",
  necessary: "Food and water are necessary for survival.",
  neglect: "Do not neglect your plants, or they will dry up.",
  negotiate: "They managed to negotiate a lower price for the car.",
  neutral: "The referee must remain neutral during the game.",
  nimble: "The nimble cat jumped easily onto the high fence.",
  nominate: "The class decided to nominate Sarah for president.",
  nonchalant: "She gave a nonchalant shrug when she won the award.",
  nonsense: "Stop talking nonsense and tell me the truth.",
  norm: "Wearing uniforms is the norm at that private school.",
  nostalgia: "Looking at old photos filled him with nostalgia.",
  notable: "The scientist made a notable discovery last week.",
  notify: "Please notify the office if you will be absent.",
  notion: "She had a sudden notion to visit the beach.",
  notorious: "The pirate was notorious for stealing gold.",
  novelty: "The novelty of the new toy wore off after a few days.",
  novice: "He is a novice at chess, but he practices daily.",
  nuance: "The actor captured every nuance of the character's emotion.",
  nuisance: "The buzzing mosquito was a constant nuisance.",
  numerous: "There are numerous birds nesting in that tree.",
  nurture: "Parents nurture their children to help them grow.",
  nutrient: "Calcium is an important nutrient for strong bones.",
  obedient: "The obedient dog sat down immediately when told.",
  object: "A strange metallic object lay on the table.",
  objective: "A judge must make an objective decision based on facts.",
  obligation: "It is your obligation to finish your chores.",
  oblivious: "He was oblivious to the loud noise because of his headphones.",
  obnoxious: "The rude customer was making an obnoxious scene.",
  obscure: "The book was written by an obscure author from the 1800s.",
  observant: "An observant detective noticed the muddy footprints.",
  obstacle: "The fallen tree was a major obstacle on the trail.",
  obstinate: "The obstinate mule refused to walk any further.",
  obtain: "You need to obtain permission before entering.",
  obvious: "It was obvious that she was happy because she was smiling.",
  occasion: "Graduation is a very formal occasion.",
  occupy: "Reading can occupy your time during a long flight.",
  occur: "Earthquakes occur without any warning.",
  ocean: "We swam in the Atlantic Ocean during vacation.",
  offend: "I did not mean to offend you with my comment.",
  ominous: "Dark, ominous clouds rolled in before the storm.",
  omit: "You can omit the last paragraph if your essay is too long.",
  opinion: "In my opinion, science is the most interesting subject.",
  opponent: "His opponent in the tennis match was very skilled.",
  opportunity: "This job is a great opportunity for my career.",
  oppose: "Many citizens oppose the plan to build a new highway.",
  optimistic: "She is optimistic that she will pass the exam.",
  option: "You have the option to take German or Spanish.",
  ordinary: "It was just an ordinary day until it started snowing.",
  organism: "A tiny bacteria is a living organism.",
  origin: "The origin of the river is high up in the mountains.",
  original: "The original painting is kept safely in a museum.",
  ornament: "We placed a shiny ornament on the tree.",
  outrageous: "The price of that simple t-shirt is outrageous.",
  overcome: "She had to overcome her fear of public speaking.",
  oxygen: "Humans need oxygen to breathe and survive.",
  pace: "He walked at a slow, steady pace.",
  pacify: "The mother tried to pacify the crying baby with a bottle.",
  painstaking: "It took painstaking effort to assemble the model ship.",
  pamphlet: "The tourist desk handed out a pamphlet about the city.",
  panic: "Don't panic if the lights go out during the storm.",
  paradox: "The phrase \"less is more\" is a well-known paradox.",
  paralyze: "The fear seemed to paralyze him for a moment.",
  paramount: "Safety is of paramount importance during a chemistry lab.",
  paraphrase: "Please paraphrase this quote instead of copying it.",
  parasite: "A flea is a parasite that feeds on dogs.",
  pardon: "Pardon me, I did not mean to interrupt.",
  participate: "Everyone is encouraged to participate in the class discussion.",
  particle: "A particle of dust got trapped in my eye.",
  particular: "Is there a particular book you are looking for?",
  passion: "She has a deep passion for playing the piano.",
  passive: "He took a passive role and let others make the decisions.",
  patience: "Teaching requires a huge amount of patience.",
  patriot: "The historical figure was a true patriot who fought for freedom.",
  patronize: "We love to patronize the local bakery down the street.",
  pause: "She made a brief pause before answering the difficult question.",
  pavilion: "We ate our lunch under the park pavilion.",
  peaceful: "The lake was quiet and peaceful in the early morning.",
  peculiar: "The milk had a peculiar smell, so I did not drink it.",
  pedestrian: "The driver stopped to let the pedestrian cross the street.",
  peer: "It is important to get feedback from a peer in class.",
  penalize: "The referee will penalize any player who trips an opponent.",
  pensive: "He sat by the window with a pensive look on his face.",
  perceive: "Cats can perceive sounds that humans cannot hear.",
  perception: "His perception of the problem changed after we talked.",
  perennial: "The garden is filled with beautiful perennial flowers.",
  perfect: "She got a perfect score on her spelling test.",
  peril: "The mountain climbers were in great peril during the blizzard.",
  perimeter: "We walked along the perimeter of the field.",
  perish: "Without water, the desert plants will perish.",
  permanent: "She used a permanent marker to label her box.",
  permissible: "It is permissible to use a calculator on the math test.",
  perpendicular: "The flagpole stands perpendicular to the ground.",
  perpetual: "The deep cave was in a state of perpetual darkness.",
  perplex: "The complex riddle seemed to perplex the entire class.",
  persevere: "If you persevere, you will eventually solve the puzzle.",
  persist: "The heavy rain will persist throughout the night.",
  personality: "She has a cheerful and outgoing personality.",
  perspective: "Travel gives you a new perspective on the world.",
  persuade: "I tried to persuade my mom to let me stay up late.",
  pertain: "These rules pertain only to the students in middle school.",
  pertinent: "Please only ask questions that are pertinent to today's lesson.",
  pessimistic: "Don't be so pessimistic about the game; we can still win!",
  petition: "The students signed a petition for longer recess times.",
  petrify: "The scary movie seemed to petrify the young audience.",
  petty: "They had a petty argument over who got to sit by the window.",
  phenomenon: "A total solar eclipse is an amazing natural phenomenon.",
  philosophy: "He likes to read books about ancient Greek philosophy.",
  phobic: "She is phobic about spiders and will scream if she sees one.",
  phrase: "The teacher highlighted a key phrase in the text.",
  physical: "Playing soccer requires a lot of physical effort.",
  physician: "The physician checked the patient's heart rate.",
  physics: "In physics class, we learned how gravity works.",
  physique: "The athlete had a strong, muscular physique.",
  pinnacle: "Winning the championship was the pinnacle of his career.",
  pioneer: "The pioneer family built a log cabin in the wilderness.",
  pious: "The pious man went to the temple every single day.",
  pique: "The mysterious title of the book served to pique my interest.",
  pirate: "The pirate searched the deserted island for buried treasure.",
  pitiful: "The cold, wet kitten looked pitiful sitting on the porch.",
  pity: "I felt great pity for the families who lost their homes.",
  pivotal: "The discovery of fire was a pivotal moment in human history.",
  placard: "He held up a large placard with the name of his team.",
  placid: "The placid surface of the lake reflected the mountains.",
  plague: "A terrible plague spread through Europe in the Middle Ages.",
  plaintiff: "The plaintiff argued that the company damaged his property.",
  plateau: "The hikers rested when they reached the top of the plateau.",
  plausible: "His explanation for being late sounded plausible.",
  plea: "The child made a tearful plea to stay up ten minutes longer.",
  pledge: "The students made a pledge to keep their school clean.",
  pliable: "The wet clay was pliable and easy to mold into a bowl.",
  plight: "The documentary detailed the plight of endangered sea turtles.",
  plot: "The movie had a confusing plot with too many twists.",
  plunder: "The invading army began to plunder the ancient village.",
  plunge: "The swimmers decided to plunge into the refreshing pool.",
  plural: "The plural form of the word \"child\" is \"children.\"",
  pneumonia: "He had to stay in the hospital while recovering from pneumonia.",
  poach: "It is illegal to poach wild animals in the national park.",
  poetry: "We read a beautiful piece of poetry in English class.",
  poignant: "The movie's ending was highly poignant and made many people cry.",
  poise: "She walked across the stage with great poise and confidence.",
  poison: "Some mushrooms contain dangerous poison.",
  polar: "Polar bears are specially adapted to live in freezing environments.",
  policy: "The school has a strict policy against bullying.",
  polish: "He used a soft cloth to polish his shoes.",
  pollute: "Factories should not pollute the nearby river with waste.",
  pompous: "The pompous actor refused to speak to his fans.",
  ponder: "She sat quietly to ponder her options for high school.",
  popular: "Pizza is a very popular food choice among kids.",
  population: "The population of our city is growing every year.",
  porous: "Sponge is a highly porous material.",
  portable: "He brought a portable speaker to play music at the beach.",
  portion: "She ate only a small portion of her dinner.",
  portray: "The author chose to portray the hero as brave but flawed.",
  pose: "The family gathered to pose for a holiday picture.",
  position: "Please return the chair to its original position.",
  positive: "Keeping a positive attitude helps you overcome challenges.",
  possess: "He does not possess a driver's license yet.",
  possibility: "There is a possibility of rain later this afternoon.",
  postpone: "We had to postpone the game due to the lightning.",
  posture: "Good posture prevents your back from hurting.",
  potent: "The medicine had a potent smell but worked quickly.",
  potential: "The teacher saw a lot of potential in the young artist.",
  pottery: "She learned how to make beautiful pottery in art class.",
  poverty: "The charity works hard to reduce poverty in the city.",
  practical: "Wearing rain boots is a practical choice on a wet day.",
  praise: "The principal called an assembly to praise the winning team.",
  prance: "The excited horse began to prance around the field.",
  precarious: "The ladder was in a precarious position against the wall.",
  precaution: "Wearing a life jacket is a smart precaution when boating.",
  precede: "A brief introduction will precede the main presentation.",
  precedent: "The court decision set a major precedent for future cases.",
  precious: "Gold is a precious metal used to make fine jewelry.",
  precise: "The scientist made precise measurements for the chemical mix.",
  precision: "The clockmaker worked with incredible precision.",
  precocious: "The precocious child was reading novels at age five.",
  predator: "The hawk is a predator that hunts small mice.",
  predecessor: "The new mayor thanked her predecessor for his hard work.",
  predict: "Meteorologists try to predict the weather accurately.",
  prediction: "My prediction is that our team will win by two points.",
  predominant: "Green was the predominant color in the landscape painting.",
  preface: "The author explained his inspiration in the book's preface.",
  prefer: "I prefer eating fresh fruit over eating candy.",
  preference: "Do you have a preference for seating, or is anywhere fine?",
  prefix: "The prefix \"un-\" means \"not,\" as in the word \"unhappy.\"",
  prehistoric: "Dinosaurs lived in prehistoric times.",
  prejudice: "Education helps people overcome cultural prejudice.",
  preliminary: "The runners competed in a preliminary race to qualify.",
  premature: "The sudden snowstorm caused a premature end to the soccer season.",
  premium: "We bought premium tickets to get the best view of the stage.",
  premonition: "She had a strange premonition that she forgot something.",
  preoccupy: "Thoughts of the upcoming test began to preoccupy his mind.",
  prepare: "You must prepare your uniform the night before school.",
  preposterous: "The idea that pigs can fly is completely preposterous.",
  prerequisite: "Taking Algebra 1 is a prerequisite for Algebra 2.",
  prescribe: "The doctor will prescribe antibiotics for your infection.",
  prescription: "Take this prescription to the pharmacy to get your medicine.",
  presence: "Your presence at the graduation ceremony means a lot to me.",
  present: "At the present moment, everyone is sitting quietly.",
  preserve: "We must work together to preserve our national parks.",
  preside: "The club vice president will preside over the meeting today.",
  president: "The president signed the new law into action.",
  prestige: "Winning the Nobel Prize carries an immense amount of prestige.",
  prestigious: "She was accepted into a highly prestigious university.",
  presume: "I presume you are tired after your long journey.",
  presumptuous: "It would be presumptuous to show up to the party uninvited.",
  pretend: "The children like to pretend they are space explorers.",
  pretense: "He dropped all pretense of anger and started laughing.",
  pretentious: "The pretentious restaurant served tiny portions on giant plates.",
  pretext: "He used the pretext of needing a pencil to talk to his friend.",
  prevail: "Justice will eventually prevail over wrongdoing.",
  prevalent: "Flu infections are more prevalent during the winter months.",
  prevent: "Wash your hands regularly to prevent the spread of germs.",
  cat: "The cat napped on the warm windowsill.",
  dog: "My dog loves to fetch the ball.",
  sun: "The sun felt warm on my face.",
  run: "I like to run around the playground.",
  hop: "The bunny began to hop across the grass.",
  big: "The elephant is a very big animal.",
  red: "She picked the red crayon to color the heart.",
  six: "I have six crayons in my box.",
  ten: "There are ten fingers on two hands.",
  mom: "My mom packed my lunch for school.",
  dad: "Dad read me a story before bed.",
  yes: "I said yes when she asked me to play.",
  wet: "My socks got wet in the puddle.",
  hot: "The soup was too hot to eat right away.",
  fun: "The carnival was so much fun.",
  bug: "A tiny bug crawled across the leaf.",
  hat: "He wore a blue hat to the beach.",
  map: "We used a map to find the park.",
  can: "I can ride my bike very fast.",
  fan: "The fan made the room feel cooler.",
  jam: "She spread jam on her toast.",
  van: "We packed the van for our trip.",
  wag: "The puppy's tail began to wag with joy.",
  tap: "Please tap the door before you walk in.",
  nap: "The baby took a nap after lunch.",
  bed: "I jumped into bed after my bath.",
  top: "We climbed to the top of the hill.",
  pig: "The pig rolled around in the mud.",
  hen: "The hen laid a fresh egg this morning.",
  fox: "A clever fox snuck past the henhouse.",
  box: "I put my toys back in the box.",
  jar: "Grandma keeps cookies in a jar.",
  jet: "The jet zoomed across the sky.",
  bat: "The bat flew out of the dark cave.",
  egg: "We cracked an egg into the bowl for breakfast.",
  cup: "She filled the cup with cold milk.",
  cap: "He wore his baseball cap backward.",
  pan: "Mom fried the eggs in a pan.",
  pot: "We planted a flower in a clay pot.",
  log: "The frog sat on a log by the pond.",
  mud: "The kids splashed in the mud after the rain.",
  mat: "Wipe your shoes on the mat before you come in.",
  rug: "The cat curled up on the cozy rug.",
  sit: "Please sit down at your desk.",
  fit: "These new shoes fit perfectly.",
  lid: "Put the lid back on the jar.",
  kid: "The kid laughed at the funny clown.",
  web: "A spider built a web in the corner.",
  zip: "Please zip up your jacket before we go outside.",
  wig: "She wore a curly wig for the school play.",
  cake: "We sang and ate chocolate cake at the party.",
  bike: "I rode my bike around the block twice.",
  home: "We hurried home before it started to rain.",
  time: "What time does the movie start?",
  like: "I like reading books about dinosaurs.",
  ride: "Can I have a ride on your scooter?",
  hope: "I hope it doesn't rain on field day.",
  cute: "The puppy looked so cute in its sweater.",
  name: "Please write your name at the top of the page.",
  game: "We played a board game after dinner.",
  hide: "Let's hide behind the curtain and surprise her.",
  side: "He sat on the side of the pool.",
  nice: "It was nice of you to share your snack.",
  rice: "We had chicken and rice for dinner.",
  line: "Stand in line to wash your hands.",
  nine: "She turned nine years old yesterday.",
  gate: "Please close the gate behind you.",
  late: "We were late for school because of traffic.",
  made: "She made a card for her grandmother.",
  lake: "We swam in the cool lake all afternoon.",
  joke: "Dad told a silly joke at dinner.",
  note: "She left a note on the kitchen table.",
  rope: "We tied the rope to the dock.",
  hole: "The dog dug a hole in the backyard.",
  cone: "I chose a waffle cone for my ice cream.",
  ship: "The ship sailed slowly out of the harbor.",
  chat: "We had a quick chat before class started.",
  that: "Can you pass me that book on the shelf?",
  when: "When does the bus arrive?",
  shop: "We went to the shop to buy bread.",
  fish: "We saw a colorful fish in the tank.",
  wish: "She made a wish before blowing out the candles.",
  chin: "He rested his chin on his hands.",
  thin: "The ice on the pond looked too thin to skate on.",
  flag: "We saluted the flag every morning.",
  frog: "The frog leaped from the lily pad.",
  stop: "The car came to a stop at the red light.",
  swim: "We love to swim in the pool every summer.",
  plan: "We made a plan for our class trip.",
  clap: "Everyone began to clap after the show.",
  drum: "He played the drum in the school band.",
  trap: "The hunter set a trap near the stream.",
  grab: "Please grab your coat before we leave.",
  glad: "I am so glad you came to my party.",
  shed: "Dad keeps the lawn mower in the shed.",
  chip: "I dropped a chip of paint off the old fence.",
  shut: "Please shut the door; it's cold outside.",
  whip: "You whip the eggs until they turn fluffy.",
  chest: "He held the puppy close to his chest.",
  plant: "We watered the plant every morning.",
  rain: "We splashed in puddles after the rain stopped.",
  boat: "We paddled the boat across the lake.",
  seed: "She planted a tiny seed in the garden.",
  tree: "We climbed the old oak tree in the yard.",
  leaf: "A red leaf floated down from the tree.",
  road: "We drove down a bumpy dirt road.",
  soap: "Wash your hands with soap before dinner.",
  coat: "Put on your coat; it's cold outside.",
  moon: "The moon glowed brightly over the lake.",
  food: "We packed snacks and food for the picnic.",
  room: "Please clean your room before company arrives.",
  book: "I read a funny book before bedtime.",
  look: "Look both ways before you cross the street.",
  cook: "Dad likes to cook pancakes on Sunday mornings.",
  star: "We wished on the first star we saw.",
  car: "We drove to the store in our car.",
  farm: "We picked apples at the farm last fall.",
  bird: "A tiny bird built a nest in the tree.",
  girl: "The girl skipped happily down the sidewalk.",
  corn: "We grilled corn for the summer cookout.",
  fork: "Use your fork to pick up the noodles.",
  ear: "He whispered the secret in her ear.",
  hear: "Did you hear the thunder last night?",
  deer: "A deer darted across the quiet road.",
  train: "We waved as the train rushed past.",
  snail: "A snail left a shiny trail on the leaf.",
  chain: "He locked his bike with a sturdy chain.",
  paint: "We used blue paint for the bedroom walls.",
  queen: "The queen wore a sparkling golden crown.",
  sleep: "Puppies need a lot of sleep to grow.",
  green: "She picked the green apple from the basket.",
  sheet: "Mom tucked a clean sheet onto my bed.",
  cloud: "That cloud looks just like a rabbit.",
  mouth: "Open your mouth wide for the dentist.",
  house: "We painted our house a cheerful shade of blue.",
  owl: "An owl hooted softly outside my window.",
  cow: "The cow grazed slowly in the green field.",
  town: "Our town has a parade every summer.",
  point: "Be careful with the point of that pencil.",
  joint: "Your elbow is a joint that lets your arm bend.",
  soil: "We mixed compost into the soil before planting.",
  coin: "She found a shiny coin on the sidewalk.",
  toy: "He shared his favorite toy with his little sister.",
  boy: "The boy raced his friend to the swing set.",
  joy: "Her face lit up with joy on her birthday.",
  royal: "The royal family waved from the palace balcony.",
  noisy: "The noisy classroom quieted down for the lesson.",
  moist: "The cake was soft and moist.",
  spoon: "She stirred her soup with a metal spoon.",
  raccoon: "A raccoon knocked over our trash can last night.",
  sunset: "We watched the orange sunset from the porch.",
  bathtub: "Rubber ducks floated in the bathtub.",
  cupcake: "She decorated her cupcake with colorful sprinkles.",
  backyard: "We played catch in the backyard after school.",
  daytime: "Owls usually sleep during the daytime.",
  weekend: "We visit my grandparents almost every weekend.",
  sunshine: "The sunshine made the whole park feel cheerful.",
  snowman: "We built a snowman with a carrot nose.",
  baseball: "He hit the baseball over the fence.",
  football: "We watched a football game on Saturday.",
  basketball: "She practices basketball every afternoon.",
  grasshopper: "A green grasshopper hopped across the lawn.",
  ladybug: "A ladybug landed gently on my finger.",
  popcorn: "We made popcorn to eat during the movie.",
  pancake: "I poured syrup all over my pancake.",
  toothbrush: "Don't forget to pack your toothbrush for the trip.",
  raincoat: "She wore her yellow raincoat to school.",
  doorbell: "The doorbell rang just as we sat down to eat.",
  mailbox: "I found a birthday card in the mailbox.",
  seesaw: "We took turns on the seesaw at recess.",
  starfish: "We found a starfish stuck to the rocks.",
  jellyfish: "A jellyfish drifted slowly past our boat.",
  goldfish: "My goldfish swims in circles in its bowl.",
  cookbook: "Grandma found the recipe in her old cookbook.",
  notebook: "I wrote my homework list in my notebook.",
  bedroom: "I keep my stuffed animals on my bedroom shelf.",
  bedtime: "Bedtime stories are my favorite part of the night.",
  daybreak: "The farmer woke at daybreak to feed the animals.",
  sunrise: "We woke up early to watch the sunrise.",
  moonlight: "The lake sparkled in the moonlight.",
  snowball: "He threw a snowball at his laughing brother.",
  earache: "She stayed home from school with an earache.",
  headache: "Loud music gave him a headache.",
  toothache: "A toothache sent her straight to the dentist.",
  stomachache: "Eating too much candy gave him a stomachache.",
  classroom: "Our classroom has a reading corner full of books.",
  homework: "I finished my homework before dinner.",
  lunchbox: "She packed a sandwich in her lunchbox.",
  suitcase: "He packed his suitcase for summer camp.",
  briefcase: "Dad carries his laptop in his briefcase.",
  eyeball: "The cartoon character's eyeball popped out in surprise.",
  eyelash: "A speck of dust landed on her eyelash.",
  fingernail: "She painted every fingernail a different color.",
  toenail: "He stubbed his toe and chipped his toenail.",
  shoelace: "His shoelace came untied during the race.",
  keyboard: "She typed her story on the computer keyboard.",
  cardboard: "We built a fort out of cardboard boxes.",
  blackboard: "The teacher wrote the spelling words on the blackboard.",
  hilltop: "We flew our kite from the hilltop.",
  treetop: "A squirrel scampered up to the treetop.",
  again: "Can we read that story again before bed?",
  every: "She waters every plant in the garden.",
  because: "We stayed inside because it was raining.",
  family: "My whole family gathered for the holiday dinner.",
  water: "Please drink some water after recess.",
  happy: "She felt happy when she saw the puppy.",
  people: "Many people came to watch the parade.",
  little: "A little kitten hid under the porch.",
  mother: "His mother packed a sandwich for lunch.",
  father: "Her father taught her how to swim.",
  sister: "My little sister borrowed my crayons.",
  color: "What color do you want to paint your room?",
  paper: "She folded the paper into a tiny airplane.",
  pencil: "He sharpened his pencil before the test.",
  school: "We walk to school together every morning.",
  eraser: "I used my eraser to fix my mistake.",
  crayon: "She picked a yellow crayon for the sun.",
  scissors: "Use the scissors carefully to cut the shape.",
  glue: "He used glue to stick the picture in his notebook.",
  ruler: "She used a ruler to draw a straight line.",
  window: "Sunlight streamed through the open window.",
  table: "We set the table before dinner.",
  chair: "He pulled up a chair to join the table.",
  floor: "The toys were scattered all over the floor.",
  wall: "We hung a painting on the living room wall.",
  kitchen: "The kitchen smelled like fresh cookies.",
  garden: "We planted tomatoes in the garden.",
  flower: "She picked a flower for her teacher.",
  grass: "The grass tickled our bare feet.",
  forest: "Deer wandered quietly through the forest.",
  river: "We watched the river rush past the bridge.",
  pond: "Frogs splashed in the pond all afternoon.",
  hill: "We rolled down the grassy hill.",
  valley: "The little town sat in a quiet valley.",
  island: "We took a boat to the small island.",
  desert: "Cactus plants grow well in the desert.",
  jungle: "Monkeys swung through the jungle trees.",
  insect: "An insect buzzed near the picnic table.",
  spider: "A spider spun its web in the corner.",
  turtle: "The turtle pulled its head into its shell.",
  rabbit: "A rabbit hopped quickly into the bushes.",
  puddle: "He jumped right into the muddy puddle.",
  weather: "The weather was perfect for a picnic.",
  season: "My favorite season is autumn.",
  winter: "It always snows here in the winter.",
  summer: "We go to the beach every summer.",
  holiday: "We decorate the house for the winter holiday.",
  birthday: "We baked a cake for her birthday.",
  carnival: "We rode the Ferris wheel at the carnival.",
  costume: "He wore a dinosaur costume to the party.",
  parade: "We cheered as the parade passed by.",
  picnic: "We packed sandwiches for our picnic in the park.",
  vacation: "Our family went to the mountains on vacation.",
  journey: "The travelers began their journey at sunrise.",
  explore: "We love to explore the woods behind our house.",
  discover: "Scientists hope to discover a new kind of frog.",
  treasure: "The pirates buried their treasure on the island.",
  dragon: "The story's brave knight battled a fierce dragon.",
  dinosaur: "The museum has a huge dinosaur skeleton.",
  robot: "The robot vacuumed the entire living room.",
  rocket: "The rocket launched into the sky with a roar.",
  planet: "Earth is the planet where we live.",
  comet: "We stayed up late to watch the comet pass.",
  galaxy: "Our solar system is part of a giant galaxy.",
  universe: "Scientists study the universe through telescopes.",
  gravity: "Gravity is why a dropped ball falls to the floor.",
  volcano: "The volcano sent smoke high into the sky.",
  glacier: "The glacier slowly carved out the valley.",
  waterfall: "We hiked for an hour to see the waterfall.",
  prairie: "Wild horses once roamed the open prairie.",
  swamp: "Alligators live in the warm, murky swamp.",
  marsh: "Herons waded through the quiet marsh.",
  harbor: "The fishing boats returned to the harbor at dusk.",
  shore: "We walked barefoot along the sandy shore.",
  wave: "A big wave knocked over our sandcastle.",
  telescope: "We used a telescope to look at the moon.",
  binoculars: "She used binoculars to spot the eagle's nest.",
  magnet: "The magnet stuck to the refrigerator door.",
  engine: "The car engine roared to life.",
  machine: "The washing machine cleaned our muddy clothes.",
  invention: "The light bulb was a famous invention.",
  discovery: "Finding the old coin was an exciting discovery.",
  scientist: "The scientist mixed chemicals in the lab.",
  experiment: "We did a science experiment with baking soda.",
  library: "We checked out three books from the library.",
  museum: "We saw dinosaur bones at the museum.",
  theater: "We watched a play at the theater downtown.",
  concert: "We sang along at the outdoor concert.",
  orchestra: "The orchestra played a beautiful song.",
  instrument: "She chose the violin as her first instrument.",
  trumpet: "He practiced the trumpet every afternoon.",
  violin: "The violin made a sweet, gentle sound.",
  guitar: "She strummed her guitar around the campfire.",
  recorder: "We learned to play a song on the recorder.",
  rhythm: "The drummer kept a steady rhythm.",
  festival: "Our town holds a fall festival every October.",
  celebration: "The whole street joined the birthday celebration.",
  ceremony: "We attended the graduation ceremony.",
  tradition: "Baking cookies together is a family tradition.",
  culture: "We learned about a different culture in school.",
  language: "She is learning a new language this year.",
  sentence: "Write a sentence using the spelling word.",
  paragraph: "Write a short paragraph about your summer.",
  vocabulary: "Reading every day builds your vocabulary.",
  dictionary: "She looked up the word in the dictionary.",
  grammar: "Good grammar makes your writing easier to read.",
  punctuation: "Remember to add punctuation at the end of each sentence.",
  question: "She raised her hand to ask a question.",
  answer: "He knew the answer right away.",
  mystery: "The detective solved the mystery of the missing necklace.",
  explorer: "The explorer crossed the icy mountains.",
  continent: "Africa is a continent with many countries.",
  country: "We visited a different country last summer.",
  nation: "The whole nation watched the big game.",
  citizen: "Every citizen has the right to vote.",
  community: "Our community cleaned up the park together.",
  neighborhood: "Kids in our neighborhood play outside every evening.",
  schedule: "Check the schedule to see when the bus arrives.",
  appointment: "She has a dentist appointment after school.",
  reminder: "I left a sticky note as a reminder.",
  message: "He left a message on the kitchen table.",
  envelope: "She sealed the card inside an envelope.",
  stamp: "Don't forget to put a stamp on the envelope.",
  postcard: "He sent us a postcard from the beach.",
  package: "A package arrived on our front porch.",
  letter: "She wrote a letter to her pen pal.",
  thoughtful: "It was thoughtful of him to save her a seat.",
  wonderful: "We had a wonderful time at the fair.",
  colorful: "The colorful kite danced in the wind.",
  helpful: "My neighbor is always helpful when I need a hand.",
  painful: "The bee sting was painful for a few minutes.",
  joyful: "The joyful crowd cheered for the winning team.",
  skillful: "The skillful chef chopped the vegetables in seconds.",
  powerful: "The powerful storm knocked down several trees.",
  useful: "A flashlight is useful during a power outage.",
  thankful: "We are thankful for our warm home.",
  grateful: "She was grateful for her friend's kindness.",
  forgetful: "My forgetful uncle always misplaces his keys.",
  playful: "The playful puppy chased its tail in circles.",
  cheerful: "Her cheerful smile made everyone feel welcome.",
  graceful: "The dancer made a graceful leap across the stage.",
  harmful: "Too much sun can be harmful to your skin.",
  truthful: "Being truthful is always the right choice.",
  respectful: "The students were respectful to their substitute teacher.",
  disrespectful: "Interrupting someone is considered disrespectful.",
  unkind: "It was unkind to laugh at his mistake.",
  unsafe: "Riding without a helmet is unsafe.",
  unsure: "She felt unsure about which answer was correct.",
  unlucky: "It was unlucky that it rained on the day of the picnic.",
  untidy: "His untidy room was covered in clothes.",
  unwise: "It would be unwise to skip studying before the test.",
  disagree: "The two friends began to disagree about the rules.",
  dislike: "I dislike getting my shoes wet in the rain.",
  disappear: "The magician made the coin disappear.",
  disconnect: "Please disconnect the cord before cleaning the toaster.",
  discomfort: "The tight shoes caused some discomfort.",
  mismatch: "He wore a funny mismatch of striped socks.",
  misunderstand: "I didn't mean to misunderstand your directions.",
  nonstop: "The toddler talked nonstop during the car ride.",
  overjoyed: "She was overjoyed when she saw the puppy.",
  underground: "Moles dig tunnels underground.",
  undersea: "The show explored strange undersea creatures.",
  outdoor: "We love outdoor games on sunny days.",
  indoor: "We have an indoor pool at our gym.",
  sunlight: "Sunlight poured through the kitchen window.",
  moonbeam: "A moonbeam lit up the quiet path.",
  starlight: "We camped under the soft starlight.",
  snowstorm: "School was canceled because of the snowstorm.",
  rainstorm: "We ran inside before the rainstorm hit.",
  thunderbolt: "A thunderbolt lit up the dark sky.",
  ambiguous: "Her ambiguous answer left us unsure if she agreed.",
  ambivalent: "He felt ambivalent about moving to a new city.",
  anomaly: "The scientist noticed an anomaly in the data.",
  antagonist: "The antagonist in the novel tries to stop the hero's plan.",
  apathy: "Voter apathy led to a very low turnout.",
  arbitrary: "The coach's arbitrary decision frustrated the team.",
  articulate: "The articulate speaker explained the plan in simple terms.",
  assimilate: "Immigrants often assimilate new customs while keeping their own traditions.",
  audacious: "Her audacious plan surprised the entire board.",
  augment: "The new hires will augment our small team.",
  austere: "The monks lived an austere life with few belongings.",
  autonomous: "The autonomous robot navigated the maze on its own.",
  benevolent: "The benevolent donor funded the entire library renovation.",
  candid: "She gave a candid review of the restaurant.",
  capricious: "The capricious weather changed from sunny to stormy in minutes.",
  catalyst: "The protest was a catalyst for new laws.",
  coherent: "He gave a coherent explanation of the accident.",
  coincide: "Her birthday happens to coincide with the school holiday.",
  compelling: "The documentary told a compelling story about the ocean.",
  complement: "The scarf was a perfect complement to her outfit.",
  comprehensive: "The teacher gave a comprehensive review before the final exam.",
  conformity: "She felt pressure to act in conformity with her classmates.",
  congruent: "Her actions were congruent with her stated values.",
  conscientious: "The conscientious student double-checked every answer.",
  contemporary: "The museum features contemporary art from local artists.",
  contradict: "His story seemed to contradict what he said yesterday.",
  conviction: "She spoke with great conviction about protecting the environment.",
  credible: "The witness gave a credible account of the accident.",
  criteria: "The judges explained the criteria for scoring the contest.",
  cynical: "His cynical comments made the meeting feel negative.",
  deduce: "The detective could deduce the culprit from the clues.",
  deficit: "The city faced a budget deficit this year.",
  deplete: "Overfishing can deplete an entire fish population.",
  deprive: "Staying up late can deprive you of needed sleep.",
  despondent: "He felt despondent after losing the championship game.",
  deteriorate: "The old bridge began to deteriorate after years of use.",
  diligent: "The diligent student finished every assignment early.",
  diminish: "Regular exercise can diminish the risk of illness.",
  discern: "It was hard to discern the path in the thick fog.",
  discrepancy: "There was a discrepancy between the two reports.",
  disdain: "She looked at the messy room with disdain.",
  dogmatic: "His dogmatic views left no room for debate.",
  dubious: "She gave him a dubious look when he explained his excuse.",
  eccentric: "Our eccentric neighbor collects vintage typewriters.",
  egregious: "The referee made an egregious error in the final minute.",
  emulate: "Young athletes often emulate their favorite players.",
  enigma: "The old house remained an enigma to the curious children.",
  ephemeral: "Cherry blossoms are known for their ephemeral beauty.",
  equilibrium: "The gymnast struggled to keep her equilibrium on the beam.",
  erratic: "The car's erratic driving worried the other drivers.",
  euphoric: "The team felt euphoric after their championship win.",
  evoke: "The old photograph evoked memories of her childhood.",
  exacerbate: "Scratching the rash will only exacerbate the itching.",
  exemplary: "Her exemplary behavior earned her a leadership award.",
  exhaustive: "The report included an exhaustive list of every option.",
  exotic: "The greenhouse was filled with exotic plants.",
  extraneous: "Remove any extraneous details from your essay.",
  facilitate: "The new software will facilitate faster communication.",
  fallacy: "It's a common fallacy that cracking knuckles causes arthritis.",
  fastidious: "The fastidious editor checked every comma twice.",
  feasible: "Is it feasible to finish the project by Friday?",
  fervent: "She is a fervent supporter of the local animal shelter.",
  flagrant: "The referee called a flagrant foul on the play.",
  fluctuate: "Prices tend to fluctuate during the holiday season.",
  formidable: "The chess champion is a formidable opponent.",
  fortuitous: "Meeting her old friend at the airport was completely fortuitous.",
  frivolous: "He spent his allowance on frivolous purchases.",
  gregarious: "Her gregarious personality made her popular at parties.",
  hindrance: "The fallen tree was a hindrance to traffic.",
  hypocrisy: "It was hypocrisy for him to criticize lateness when he was late himself.",
  hypothesis: "The students tested their hypothesis with a simple experiment.",
};
